#! /bin/sh

if ! pgrep -x /usr/local/bin/panel > /dev/null
then
    panel &
fi

if ! pgrep -x /usr/local/bin/sxhkd > /dev/null
then
    sxhkd &
fi

bspc monitor HDMI2 -d I II III IV V
bspc monitor HDMI1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config click_to_focus true
bspc config pointer_follows_monitor       true
bspc config pointer_modifier              mod1
bspc node pointer -f

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop -f ^1

bspc config focused_border_color "#f441af"

bspc rule -a scratchpad sticky=on state=floating hidden=on
st -c scratchpad -e ~/bin/scratch &

# bspc rule -a Google-chrome desktop='^8' state=floating
# bspc rule -a Termite desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
