#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(dirname "$(git rev-parse --absolute-git-dir)")"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
