#! /bin/sh

if ! pgrep -x /usr/local/bin/panel > /dev/null
then
    panel &
fi

if ! pgrep -x /usr/local/bin/sxhkd > /dev/null
then
    sxhkd &
fi

if [[ $(hostname) == 'athena' ]]; then
    bspc monitor HDMI2 -d I II III IV V
    bspc monitor HDMI1 -d VI VII VIII IX X
elif [[ $(hostname) == 'aphrodite' ]]; then
    bspc monitor LVDS-1 -d I II III IV V VI VII VIII IX X
fi


bspc config border_width         3
bspc config window_gap          12

bspc config click_to_focus true
bspc config pointer_follows_monitor       true
bspc config pointer_modifier              mod1
bspc node pointer -f

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop -f ^1

bspc config focused_border_color "#f441af"

feh --bg-center /home/bryan/Dropbox/photos/backgrounds/arch_blue_bg.jpeg
