// file generated by /getstrings script, do not edit. 
 var i18n_data = {
  "de": {
    "camel_icon_tip": [
      null,
      "Der Camelizer v%{version_number} - Klicke auf das Zeichen, um Bugs zu melden oder neue Funktionen vorzuschlagen."
    ],
    "products_heading": [
      null,
      "Produkte auf dieser Seite. Klicke auf einen Link, um den Preisverlauf zu sehen."
    ],
    "t_1m": [
      null,
      "1m"
    ],
    "t_1y": [
      null,
      "1j"
    ],
    "t_3m": [
      null,
      "3m"
    ],
    "t_3rd_party_new": [
      null,
      "Neu Drittanbieter"
    ],
    "t_3rd_party_used": [
      null,
      "Gebraucht Drittanbieter"
    ],
    "t_6m": [
      null,
      "6m"
    ],
    "t_add_wishlist": [
      null,
      "Wunschzettel hinzufügen"
    ],
    "t_add_wishlists": [
      null,
      "Wunschzettel hinzufügen"
    ],
    "t_add_your_amazon_wishlist_to_your_camel_account": [
      null,
      "Füge deinen Amazon-Wunschzettel zu deinem CAmel-Account hinzu und wir synchronisieren ihn dann mit deinen Preisüberwachungen, indem wir neue Preisüberwachungen erstellen und wenn nötig andere als \"gekauft\" kennzeichnen."
    ],
    "t_all": [
      null,
      "alle"
    ],
    "t_amazon": [
      null,
      "Amazon"
    ],
    "t_amazon_price_discount": [
      null,
      "Amazon-Preisrabatt"
    ],
    "t_an_error_has_occurred": [
      null,
      "Es ist ein Fehler aufgetreten."
    ],
    "t_are_you_sure_you_want_to_delete_this_price_watch": [
      null,
      "Bist du sicher, dass du diese Preisüberwachungen löschen möchtest?"
    ],
    "t_camelcamelcamel_users_don_t_enter_their_email_addr": [
      null,
      "CamelCamelCamel-Benutzer müssen ihre E-Mail-Adressen nicht angeben."
    ],
    "t_cancel": [
      null,
      "Abbrechen"
    ],
    "t_chart": [
      null,
      "Diagramm"
    ],
    "t_chart_options": [
      null,
      "Diagrammoptionen"
    ],
    "t_close_up_view": [
      null,
      "Detailansicht"
    ],
    "t_create_a_wishlist_and_then_you_can_import_it": [
      null,
      "Erstelle einen Wunschzettel und dann kannst du ihn importieren."
    ],
    "t_create_price_watch": [
      null,
      "Preisüberwachungen erstellen"
    ],
    "t_create_price_watches": [
      null,
      "Preisüberwachungen erstellen"
    ],
    "t_create_price_watches_these_price_types_please_choo": [
      null,
      "Preisüberwachungen für diese Preistypen auswählen (Bitte wähle mindestens einen):"
    ],
    "t_current": [
      null,
      "Aktuell"
    ],
    "t_current_price": [
      null,
      "Aktueller Preis"
    ],
    "t_date_range": [
      null,
      "Datenbereich"
    ],
    "t_delete": [
      null,
      "löschen"
    ],
    "t_desired": [
      null,
      "Gewünscht"
    ],
    "t_desired_price": [
      null,
      "Wunschpreis"
    ],
    "t_edit": [
      null,
      "Bearbeiten"
    ],
    "t_email_address": [
      null,
      "E-Mail-Adresse:"
    ],
    "t_enter_your_desired_prices_we_ll_notify_when_they_a": [
      null,
      "Gib deine Wunschpreise ein und wir benachrichtigen dich, wenn sie erreicht werden"
    ],
    "t_helpful_links": [
      null,
      "Nützliche Links"
    ],
    "t_highest": [
      null,
      "Höchster"
    ],
    "t_it_looks_like_you_don_t_have_any_amazon_wishlists": [
      null,
      "Es sieht so aus, als ob du keine Amazon-Wunschzettel hast."
    ],
    "t_item": [
      null,
      "1 Artikel"
    ],
    "t_items": [
      null,
      "%{count} Artikel"
    ],
    "t_loading": [
      null,
      "Lädt..."
    ],
    "t_log_in": [
      null,
      "Anmelden"
    ],
    "t_lowest": [
      null,
      "Niedrigste"
    ],
    "t_lowest_price": [
      null,
      "Niedrigster Preis"
    ],
    "t_newegg_price": [
      null,
      "Newegg-Preis"
    ],
    "t_not_in_stock": [
      null,
      "Nicht auf Lager"
    ],
    "t_ok": [
      null,
      "OK"
    ],
    "t_please_choose_at_least_one_price_type": [
      null,
      "Bitte wähle mindestens einen Preistyp."
    ],
    "t_please_choose_least_one_wishlist_already_imported": [
      null,
      "Bitte wähle mindestens einen Wunschzettel, den du noch nicht importiert hast."
    ],
    "t_please_enter_a_valid_number": [
      null,
      "Bitte gib eine gültige Nummer ein"
    ],
    "t_please_enter_a_valid_relative_value": [
      null,
      "Bitte gib einen gültigen relativen Wert an"
    ],
    "t_please_enter_a_watch_price_below_the_current_price": [
      null,
      "Bitte gib einen Überwachungspreis unter dem aktuellen Preis ein"
    ],
    "t_please_enter_your_email_address": [
      null,
      "Bitte gib deine E-Mail-Adresse ein"
    ],
    "t_please_sign_in_to_amazon_first": [
      null,
      "Bitte melde dich erst bei Amazon an."
    ],
    "t_price_type": [
      null,
      "Preistyp"
    ],
    "t_price_types": [
      null,
      "Preistypen"
    ],
    "t_prices_are_set_relative_selected_price_measure_cur": [
      null,
      "Die Preise werden nach dem gewählten Preismaß aufgestellt und in der Währung der örtlichen Einstellung des verfolgten Produkts angegeben. Wähle \"Statischer Preis\", wenn du den Wunschpreis aller neuen Preisüberwachungen auf den festgelegten Wert einstellen möchtest."
    ],
    "t_product_data_downloaded_loading_chart_image": [
      null,
      "Produktdaten heruntergeladen, Diagramm wird geladen..."
    ],
    "t_product_not_found_we_will_attempt_to_find_it_and_add_it_to_our_database_so_please_check_again_later": [
      null,
      "Produkt nicht gefunden. Wir versuchen es zu finden und zu unserer Datenbank hinzuzufügen, also versuche es später noch einmal."
    ],
    "t_products_on_this_page": [
      null,
      "Produkte auf dieser Seite"
    ],
    "t_remove_extreme_values": [
      null,
      "Extremwerte entfernen"
    ],
    "t_sale_price": [
      null,
      "Verkaufspreis"
    ],
    "t_saving": [
      null,
      "Speichert..."
    ],
    "t_service_temporarily_unavailable": [
      null,
      "Service vorübergehend nicht verfügbar"
    ],
    "t_set_desired_price": [
      null,
      "Wunschpreis feststellen"
    ],
    "t_set_the_desired_price_to_the": [
      null,
      "Stelle den Wunschpreis auf"
    ],
    "t_sign_up": [
      null,
      "Registrieren"
    ],
    "t_signed_in_as": [
      null,
      "Angemeldet als %{username}"
    ],
    "t_sorry_we_couldn_t_find_your_wishlists_please_make": [
      null,
      "Wir konnten leider deine Wunschliste nicht finden. Bitte vergewissere dich, dass du auf Amazon angemeldet bist, und versuche es noch einmal."
    ],
    "t_static_price": [
      null,
      "Statischer Preis"
    ],
    "t_there_was_an_error_changing_privacy_your_wishlist": [
      null,
      "Während der Änderung der Privatsphäre deines Wunschzettels ist ein Fehler aufgetreten."
    ],
    "t_there_was_an_error_deleting_your_imported_wishlist": [
      null,
      "Beim Löschen deines Wunschzettels ist ein Fehler aufgetreten."
    ],
    "t_there_was_an_error_importing_your_wishlists": [
      null,
      "Beim Import deines Wunschzettels ist ein Fehler aufgetreten"
    ],
    "t_there_was_an_error_saving_your_price_watches": [
      null,
      "Beim Speichern deiner Preisüberwachungen ist ein Fehler aufgetreten"
    ],
    "t_this_is_because_it_is_either_not_a_supported_retailer_site_or_because_this_page_uses_https": [
      null,
      "Das liegt entweder daran, dass es sich nicht um einen unterstützten Händler handelt, oder daran, dass diese Seite HTTPS verwendet."
    ],
    "t_this_site_or_page_is_not_supported_by_the_camelizer": [
      null,
      "Diese Seite wird von The Camelizer nicht unterstützt."
    ],
    "t_update_price_watch": [
      null,
      "Preisüberwachung aktualisieren"
    ],
    "t_update_price_watches": [
      null,
      "Preisüberwachungen aktualisieren"
    ],
    "t_view_all_data": [
      null,
      "Alle Daten ansehen"
    ],
    "t_view_data_for_the_last_3_months": [
      null,
      "Daten der letzten drei Monate ansehen"
    ],
    "t_view_data_for_the_last_6_months": [
      null,
      "Daten der letzten sechs Monate ansehen"
    ],
    "t_view_data_for_the_last_month": [
      null,
      "Daten des letzten Monats ansehen"
    ],
    "t_view_data_for_the_last_year": [
      null,
      "Daten für das letzte Jahr ansehen"
    ],
    "t_view_product_on_3camels": [
      null,
      "Produkte auf 3Camels ansehen"
    ],
    "t_view_product_on_retailer": [
      null,
      "Produkt auf %{retailer} ansehen"
    ],
    "t_we_re_not_tracking_but_will_be_soon": [
      null,
      "Wir verfolgen noch nicht, aber bald:"
    ],
    "t_wishlist_note": [
      null,
      "Dein Wunschzettel muss zum synchronisieren entweder geteilt oder öffentlich sein."
    ],
    "t_wishlist_private": [
      null,
      "Privat"
    ],
    "t_wishlist_public": [
      null,
      "Öffentlich"
    ],
    "t_wishlist_shared": [
      null,
      "Geteilt"
    ],
    "t_wishlists": [
      null,
      "Wunschzettel"
    ],
    "t_you_need_to_choose_a_product_from_a_href_the_list_of_products_on_this_page_a": [
      null,
      "Du musst ein Produkt von der Produktliste auf dieser Seite wählen."
    ],
    "t_your_wishlist_has_been_queued_processing_we_ll_not": [
      null,
      "Dein Wunschzettel wird demnächst bearbeitet. Wir benachrichtigen dich, wenn dies abgeschlossen ist."
    ],
    "t_your_wishlists_have_been_queued_for_processing": [
      null,
      "Dein Wunschzettel wird demnächst bearbeitet."
    ],
    "title": [
      null,
      "Der Camelizer - Amazon-Preisverfolger"
    ],
    "": {
      "domain": "de",
      "lang": "de",
      "plural-forms": "nplurals=2; plural=(n != 1);"
    }
  },
  "en": {
    "camel_icon_tip": [
      null,
      "The Camelizer v%{version_number} - Click the icon to report bugs or suggest new features."
    ],
    "products_heading": [
      null,
      "Products on this page. Click a link to see price history."
    ],
    "t_1m": [
      null,
      "1m"
    ],
    "t_1y": [
      null,
      "1y"
    ],
    "t_3m": [
      null,
      "3m"
    ],
    "t_3rd_party_new": [
      null,
      "3rd Party New"
    ],
    "t_3rd_party_used": [
      null,
      "3rd Party Used"
    ],
    "t_6m": [
      null,
      "6m"
    ],
    "t_add_wishlist": [
      null,
      "Add Wishlist"
    ],
    "t_add_wishlists": [
      null,
      "Add Wishlists"
    ],
    "t_add_your_amazon_wishlist_to_your_camel_account": [
      null,
      "Add your Amazon Wishlist to your Camel account and we'll periodically synchronize the wishlist to your price watches list, creating new price watches and marking existing ones as purchased, as necessary."
    ],
    "t_all": [
      null,
      "all"
    ],
    "t_amazon": [
      null,
      "Amazon"
    ],
    "t_amazon_price_discount": [
      null,
      "Amazon Price Discount"
    ],
    "t_an_error_has_occurred": [
      null,
      "An error has occurred."
    ],
    "t_are_you_sure_you_want_to_delete_this_price_watch": [
      null,
      "Are you sure you want to delete this price watch?"
    ],
    "t_camelcamelcamel_users_don_t_enter_their_email_addr": [
      null,
      "CamelCamelCamel users don't have to enter their email addresses."
    ],
    "t_cancel": [
      null,
      "Cancel"
    ],
    "t_chart": [
      null,
      "Chart"
    ],
    "t_chart_options": [
      null,
      "Chart Options"
    ],
    "t_close_up_view": [
      null,
      "Close-up View"
    ],
    "t_create_a_wishlist_and_then_you_can_import_it": [
      null,
      "Create a wishlist and then you can import it."
    ],
    "t_create_price_watch": [
      null,
      "Create Price Watch"
    ],
    "t_create_price_watches": [
      null,
      "Create Price Watches"
    ],
    "t_create_price_watches_these_price_types_please_choo": [
      null,
      "Create price watches for these price types (please choose at least one):"
    ],
    "t_current": [
      null,
      "Current"
    ],
    "t_current_price": [
      null,
      "Current Price"
    ],
    "t_date_range": [
      null,
      "Date Range"
    ],
    "t_delete": [
      null,
      "delete"
    ],
    "t_desired": [
      null,
      "Desired"
    ],
    "t_desired_price": [
      null,
      "Desired Price"
    ],
    "t_edit": [
      null,
      "Edit"
    ],
    "t_email_address": [
      null,
      "Email Address:"
    ],
    "t_enter_your_desired_prices_we_ll_notify_when_they_a": [
      null,
      "Enter your desired prices and we'll notify you when they are achieved"
    ],
    "t_helpful_links": [
      null,
      "Helpful Links"
    ],
    "t_highest": [
      null,
      "Highest"
    ],
    "t_it_looks_like_you_don_t_have_any_amazon_wishlists": [
      null,
      "It looks like you don't have any Amazon wishlists."
    ],
    "t_item": [
      null,
      "1 item"
    ],
    "t_items": [
      null,
      "%{count} items"
    ],
    "t_loading": [
      null,
      "Loading..."
    ],
    "t_log_in": [
      null,
      "Log in"
    ],
    "t_lowest": [
      null,
      "Lowest"
    ],
    "t_lowest_price": [
      null,
      "Lowest Price"
    ],
    "t_newegg_price": [
      null,
      "Newegg Price"
    ],
    "t_not_in_stock": [
      null,
      "Not in Stock"
    ],
    "t_ok": [
      null,
      "OK"
    ],
    "t_please_choose_at_least_one_price_type": [
      null,
      "Please choose at least one price type."
    ],
    "t_please_choose_least_one_wishlist_already_imported": [
      null,
      "Please choose at least one wishlist that you have not already imported."
    ],
    "t_please_enter_a_valid_number": [
      null,
      "Please enter a valid number"
    ],
    "t_please_enter_a_valid_relative_value": [
      null,
      "Please enter a valid relative value"
    ],
    "t_please_enter_a_watch_price_below_the_current_price": [
      null,
      "Please enter a watch price below the current price"
    ],
    "t_please_enter_your_email_address": [
      null,
      "Please enter your email address"
    ],
    "t_please_sign_in_to_amazon_first": [
      null,
      "Please sign in to Amazon first."
    ],
    "t_price_type": [
      null,
      "Price Type"
    ],
    "t_price_types": [
      null,
      "Price Types"
    ],
    "t_prices_are_set_relative_selected_price_measure_cur": [
      null,
      "Prices are set relative to the selected price measure and in the currency associated with the locale of the tracked product. Choose \"Static Price\" if you want to set the desired price of all new price watches to the specified value."
    ],
    "t_product_data_downloaded_loading_chart_image": [
      null,
      "Product data downloaded, loading chart image..."
    ],
    "t_product_not_found_we_will_attempt_to_find_it_and_add_it_to_our_database_so_please_check_again_later": [
      null,
      "Product not found.  We will attempt to find it and add it to our database, so please check again later."
    ],
    "t_products_on_this_page": [
      null,
      "Products On This Page"
    ],
    "t_remove_extreme_values": [
      null,
      "Remove Extreme Values"
    ],
    "t_sale_price": [
      null,
      "Sale Price"
    ],
    "t_saving": [
      null,
      "Saving..."
    ],
    "t_service_temporarily_unavailable": [
      null,
      "Service Temporarily Unavailable"
    ],
    "t_set_desired_price": [
      null,
      "Set Desired Price"
    ],
    "t_set_the_desired_price_to_the": [
      null,
      "Set the desired price to the"
    ],
    "t_sign_up": [
      null,
      "Sign up"
    ],
    "t_signed_in_as": [
      null,
      "Signed in as %{username}"
    ],
    "t_sorry_we_couldn_t_find_your_wishlists_please_make": [
      null,
      "Sorry, we couldn't find your wishlists. Please make sure you're signed in to Amazon and try again."
    ],
    "t_static_price": [
      null,
      "Static Price"
    ],
    "t_there_was_an_error_changing_privacy_your_wishlist": [
      null,
      "There was an error changing the privacy of your wishlist."
    ],
    "t_there_was_an_error_deleting_your_imported_wishlist": [
      null,
      "There was an error deleting your imported wishlist."
    ],
    "t_there_was_an_error_importing_your_wishlists": [
      null,
      "There was an error importing your wishlists"
    ],
    "t_there_was_an_error_saving_your_price_watches": [
      null,
      "There was an error saving your price watches"
    ],
    "t_this_is_because_it_is_either_not_a_supported_retailer_site_or_because_this_page_uses_https": [
      null,
      "This is because it is either not a supported retailer site or because this page uses HTTPS."
    ],
    "t_this_site_or_page_is_not_supported_by_the_camelizer": [
      null,
      "This site or page is not supported by The Camelizer."
    ],
    "t_update_price_watch": [
      null,
      "Update Price Watch"
    ],
    "t_update_price_watches": [
      null,
      "Update Price Watches"
    ],
    "t_view_all_data": [
      null,
      "View all data"
    ],
    "t_view_data_for_the_last_3_months": [
      null,
      "View data for the last 3 months"
    ],
    "t_view_data_for_the_last_6_months": [
      null,
      "View data for the last 6 months"
    ],
    "t_view_data_for_the_last_month": [
      null,
      "View data for the last month"
    ],
    "t_view_data_for_the_last_year": [
      null,
      "View data for the last year"
    ],
    "t_view_product_on_3camels": [
      null,
      "View Product on 3Camels"
    ],
    "t_view_product_on_retailer": [
      null,
      "View product on %{retailer}"
    ],
    "t_we_re_not_tracking_but_will_be_soon": [
      null,
      "We're not tracking, but will be soon:"
    ],
    "t_wishlist_note": [
      null,
      "Your wishlist must be either shared or public to sync."
    ],
    "t_wishlist_private": [
      null,
      "Private"
    ],
    "t_wishlist_public": [
      null,
      "Public"
    ],
    "t_wishlist_shared": [
      null,
      "Shared"
    ],
    "t_wishlists": [
      null,
      "Wishlists"
    ],
    "t_you_need_to_choose_a_product_from_a_href_the_list_of_products_on_this_page_a": [
      null,
      "You need to choose a product from the list of products on this page."
    ],
    "t_your_wishlist_has_been_queued_processing_we_ll_not": [
      null,
      "Your wishlist has been queued for processing. We'll notify you upon its completion."
    ],
    "t_your_wishlists_have_been_queued_for_processing": [
      null,
      "Your wishlists have been queued for processing."
    ],
    "title": [
      null,
      "The Camelizer - Amazon Price Tracker"
    ],
    "": {
      "domain": "en",
      "lang": "en",
      "plural-forms": "nplurals=2; plural=(n != 1);"
    }
  },
  "es": {
    "camel_icon_tip": [
      null,
      "El Camelizer v%{version_number} - haz clic en el icono para informar de errores o sugerencias."
    ],
    "products_heading": [
      null,
      "Productos en esta página. Haz clic aquí para ver el historial de precio."
    ],
    "t_1m": [
      null,
      "1m"
    ],
    "t_1y": [
      null,
      "1a"
    ],
    "t_3m": [
      null,
      "3m"
    ],
    "t_3rd_party_new": [
      null,
      "Artículo nuevo de tercero"
    ],
    "t_3rd_party_used": [
      null,
      "Artículo usado de tercero"
    ],
    "t_6m": [
      null,
      "6m"
    ],
    "t_add_wishlist": [
      null,
      "Agregar lista de deseos"
    ],
    "t_add_wishlists": [
      null,
      "Añadir Lista de deseos"
    ],
    "t_add_your_amazon_wishlist_to_your_camel_account": [
      null,
      "Añade tu lista de deseos de Amazon a tu cuenta Camel y sincronizaremos de forma periódica tu lista con tus seguimientos de precio, creando nuevos seguimientos y marcando los ya existentes como comprados cuando sea necesario."
    ],
    "t_all": [
      null,
      "todos"
    ],
    "t_amazon": [
      null,
      "Amazon"
    ],
    "t_amazon_price_discount": [
      null,
      "Descuento de precio Amazon"
    ],
    "t_an_error_has_occurred": [
      null,
      "Se ha producido un error."
    ],
    "t_are_you_sure_you_want_to_delete_this_price_watch": [
      null,
      "¿Seguro que quieres borrar este seguimiento?"
    ],
    "t_camelcamelcamel_users_don_t_enter_their_email_addr": [
      null,
      "Los usuarios CamelCamelCamel no deben introducir su email."
    ],
    "t_cancel": [
      null,
      "Cancelar"
    ],
    "t_chart": [
      null,
      "Gráfica"
    ],
    "t_chart_options": [
      null,
      "Opciones de grafica"
    ],
    "t_close_up_view": [
      null,
      "Vista en detalle"
    ],
    "t_create_a_wishlist_and_then_you_can_import_it": [
      null,
      "Crea una lista de deseos e impórtala"
    ],
    "t_create_price_watch": [
      null,
      "Crear seguimiento"
    ],
    "t_create_price_watches": [
      null,
      "Crear seguimientos"
    ],
    "t_create_price_watches_these_price_types_please_choo": [
      null,
      "Crear seguimientos de precio para estos tipos de precio (elige al menos uno):"
    ],
    "t_current": [
      null,
      "Actual"
    ],
    "t_current_price": [
      null,
      "Precio actual"
    ],
    "t_date_range": [
      null,
      "Periodo"
    ],
    "t_delete": [
      null,
      "borrar"
    ],
    "t_desired": [
      null,
      "Deseado"
    ],
    "t_desired_price": [
      null,
      "Precio deseado"
    ],
    "t_edit": [
      null,
      "Editar"
    ],
    "t_email_address": [
      null,
      "Email:"
    ],
    "t_enter_your_desired_prices_we_ll_notify_when_they_a": [
      null,
      "Introduce tus precios deseados y te lo comunicaremos"
    ],
    "t_helpful_links": [
      null,
      "Enlaces útiles"
    ],
    "t_highest": [
      null,
      "Más alto"
    ],
    "t_it_looks_like_you_don_t_have_any_amazon_wishlists": [
      null,
      "Parece que no tienes ninguna lista de deseos Amazon."
    ],
    "t_item": [
      null,
      "1 elemento"
    ],
    "t_items": [
      null,
      "%{count} elementos"
    ],
    "t_loading": [
      null,
      "Cargando..."
    ],
    "t_log_in": [
      null,
      "Login"
    ],
    "t_lowest": [
      null,
      "Más bajo"
    ],
    "t_lowest_price": [
      null,
      "Precio más bajo"
    ],
    "t_newegg_price": [
      null,
      "Precio Newegg"
    ],
    "t_not_in_stock": [
      null,
      "Fuera de stock"
    ],
    "t_ok": [
      null,
      "Aceptar"
    ],
    "t_please_choose_at_least_one_price_type": [
      null,
      "Elige al menos tipo de precio."
    ],
    "t_please_choose_least_one_wishlist_already_imported": [
      null,
      "Elige al menos una lista de deseo que no hayas importado."
    ],
    "t_please_enter_a_valid_number": [
      null,
      "Introduce un número válido"
    ],
    "t_please_enter_a_valid_relative_value": [
      null,
      "Introduce un valor relativo válido"
    ],
    "t_please_enter_a_watch_price_below_the_current_price": [
      null,
      "Introduce un precio de seguimiento debajo del precio actual"
    ],
    "t_please_enter_your_email_address": [
      null,
      "Introduce tu email"
    ],
    "t_please_sign_in_to_amazon_first": [
      null,
      "Inicia sesión en Amazón."
    ],
    "t_price_type": [
      null,
      "Tipo de precio"
    ],
    "t_price_types": [
      null,
      "Tipos de precio"
    ],
    "t_prices_are_set_relative_selected_price_measure_cur": [
      null,
      "Los precios se fijan en relación a la medida del precio seleccionado y en la moneda asociada a la configuración regional del producto seguido. Elige \"Precio estático\" si quieres que el precio deseado se aplique a todos los seguimientos nuevos."
    ],
    "t_product_data_downloaded_loading_chart_image": [
      null,
      "Datos de producto descargados, cargando imagen de gráfica..."
    ],
    "t_product_not_found_we_will_attempt_to_find_it_and_add_it_to_our_database_so_please_check_again_later": [
      null,
      "Producto no encontrado. Intentaremos encontrarlo y añadirlo a nuestra base de datos. Vuelve a intentarlo en otra ocasión."
    ],
    "t_products_on_this_page": [
      null,
      "Productos en esta página"
    ],
    "t_remove_extreme_values": [
      null,
      "Quitar valores extremos"
    ],
    "t_sale_price": [
      null,
      "Precio de venta"
    ],
    "t_saving": [
      null,
      "Guardando..."
    ],
    "t_service_temporarily_unavailable": [
      null,
      "Servicio temporalmente no disponible"
    ],
    "t_set_desired_price": [
      null,
      "Fijar el precio deseado"
    ],
    "t_set_the_desired_price_to_the": [
      null,
      "Fijar el precio deseado a"
    ],
    "t_sign_up": [
      null,
      "Registrarse"
    ],
    "t_signed_in_as": [
      null,
      "Iniciar sesión como %{username}"
    ],
    "t_sorry_we_couldn_t_find_your_wishlists_please_make": [
      null,
      "No hemos podido encontrar tus listas de deseos. Comprueba que hayas iniciado la sesión en Amazon y vuelve a intentarlo."
    ],
    "t_static_price": [
      null,
      "Precio estático"
    ],
    "t_there_was_an_error_changing_privacy_your_wishlist": [
      null,
      "Se ha producido un error al cambiar la privacidad"
    ],
    "t_there_was_an_error_deleting_your_imported_wishlist": [
      null,
      "Se ha producido un error al borrar la lista de deseos importada."
    ],
    "t_there_was_an_error_importing_your_wishlists": [
      null,
      "Se ha producido un error al importar tus listas de deseo"
    ],
    "t_there_was_an_error_saving_your_price_watches": [
      null,
      "Se ha producido un error al guardar tus seguimientos de precio."
    ],
    "t_this_is_because_it_is_either_not_a_supported_retailer_site_or_because_this_page_uses_https": [
      null,
      "Esto puede deberse a que esta página utiliza HTTPS o no es un página de vendedor compatible."
    ],
    "t_this_site_or_page_is_not_supported_by_the_camelizer": [
      null,
      "Sitio o página no compatible con The Camelizer."
    ],
    "t_update_price_watch": [
      null,
      "Actualizar seguimiento"
    ],
    "t_update_price_watches": [
      null,
      "Actualizar seguimientos"
    ],
    "t_view_all_data": [
      null,
      "Ver todos los datos"
    ],
    "t_view_data_for_the_last_3_months": [
      null,
      "Ver datos de los últimos 3 meses"
    ],
    "t_view_data_for_the_last_6_months": [
      null,
      "Ver datos de los últimos 6 meses"
    ],
    "t_view_data_for_the_last_month": [
      null,
      "Ver datos del último mes"
    ],
    "t_view_data_for_the_last_year": [
      null,
      "Ver datos del último año"
    ],
    "t_view_product_on_3camels": [
      null,
      "Ver productos en 3Camels"
    ],
    "t_view_product_on_retailer": [
      null,
      "Ver producto en %{retailer}"
    ],
    "t_we_re_not_tracking_but_will_be_soon": [
      null,
      "No estamos siguiendo, pero pronto lo haremos:"
    ],
    "t_wishlist_note": [
      null,
      "Tu lista de deseo debe ser compartida o pública para su sincronización."
    ],
    "t_wishlist_private": [
      null,
      "Privado"
    ],
    "t_wishlist_public": [
      null,
      "Público"
    ],
    "t_wishlist_shared": [
      null,
      "Compartido"
    ],
    "t_wishlists": [
      null,
      "Listas de deseo"
    ],
    "t_you_need_to_choose_a_product_from_a_href_the_list_of_products_on_this_page_a": [
      null,
      "Debes elegir un producto de la lista de productos de esta página"
    ],
    "t_your_wishlist_has_been_queued_processing_we_ll_not": [
      null,
      "El procesado de tu lista de deseos está en cola. Te avisaremos tan pronto como se complete."
    ],
    "t_your_wishlists_have_been_queued_for_processing": [
      null,
      "Tus listas de deseo están en cola para su procesado."
    ],
    "title": [
      null,
      "El Camelizer - Seguidor de precios Amazon"
    ],
    "": {
      "domain": "es",
      "lang": "es",
      "plural-forms": "nplurals=2; plural=(n != 1);"
    }
  },
  "fr": {
    "camel_icon_tip": [
      null,
      "Le Camelizer v%{version_number} - Cliquez sur l'icône pour commenter des bugs ou suggérer de nouvelles fonctions."
    ],
    "products_heading": [
      null,
      "Produits sur cette page. Cliquez sur un lien pour consulter un historique de prix."
    ],
    "t_1m": [
      null,
      "1m"
    ],
    "t_1y": [
      null,
      "1a"
    ],
    "t_3m": [
      null,
      "3m"
    ],
    "t_3rd_party_new": [
      null,
      "Prix neuf d'un tiers"
    ],
    "t_3rd_party_used": [
      null,
      "Prix d'occasion d'un tiers"
    ],
    "t_6m": [
      null,
      "6m"
    ],
    "t_add_wishlist": [
      null,
      "Ajouter une liste d'envies"
    ],
    "t_add_wishlists": [
      null,
      "Ajouter des listes d'envies"
    ],
    "t_add_your_amazon_wishlist_to_your_camel_account": [
      null,
      "Ajoutez votre liste d'envies Amazon à votre compte Camel et nous la synchroniserons périodiquement avec votre liste de suivis de prix, afin de créer de nouveaux suivis de prix et de marquer ceux existants comme achetés, le cas échéant."
    ],
    "t_all": [
      null,
      "tout"
    ],
    "t_amazon": [
      null,
      "Amazon"
    ],
    "t_amazon_price_discount": [
      null,
      "Remise sur prix Amazon"
    ],
    "t_an_error_has_occurred": [
      null,
      "Une erreur est survenue."
    ],
    "t_are_you_sure_you_want_to_delete_this_price_watch": [
      null,
      "Êtes-vous sûr(e) de vouloir supprimer ce suivi de prix ?"
    ],
    "t_camelcamelcamel_users_don_t_enter_their_email_addr": [
      null,
      "Les utilisateurs CamelCamelCamel n'ont pas à saisir leur adresse e-mail."
    ],
    "t_cancel": [
      null,
      "Annuler"
    ],
    "t_chart": [
      null,
      "Graphique"
    ],
    "t_chart_options": [
      null,
      "Options de graphique"
    ],
    "t_close_up_view": [
      null,
      "Vue détaillée"
    ],
    "t_create_a_wishlist_and_then_you_can_import_it": [
      null,
      "Créez une liste d'envies que vous pourrez ensuite importer."
    ],
    "t_create_price_watch": [
      null,
      "Créer un suivi de prix"
    ],
    "t_create_price_watches": [
      null,
      "Créer des suivis de prix"
    ],
    "t_create_price_watches_these_price_types_please_choo": [
      null,
      "Créez des suivis de prix pour ces types de prix (choisissez-en au moins un) :"
    ],
    "t_current": [
      null,
      "Actuel"
    ],
    "t_current_price": [
      null,
      "Prix actuel"
    ],
    "t_date_range": [
      null,
      "Intervalle de dates"
    ],
    "t_delete": [
      null,
      "supprimer"
    ],
    "t_desired": [
      null,
      "Souhaité"
    ],
    "t_desired_price": [
      null,
      "Prix souhaité"
    ],
    "t_edit": [
      null,
      "Éditer"
    ],
    "t_email_address": [
      null,
      "Adresse e-mail :"
    ],
    "t_enter_your_desired_prices_we_ll_notify_when_they_a": [
      null,
      "Saisissez vos prix souhaités et nous vous avertirons lorsqu'ils seront atteints"
    ],
    "t_helpful_links": [
      null,
      "Liens utiles"
    ],
    "t_highest": [
      null,
      "Le plus haut"
    ],
    "t_it_looks_like_you_don_t_have_any_amazon_wishlists": [
      null,
      "Il semble que vous n'avez aucune liste d'envies Amazon."
    ],
    "t_item": [
      null,
      "1 article"
    ],
    "t_items": [
      null,
      "%{count} articles"
    ],
    "t_loading": [
      null,
      "Chargement..."
    ],
    "t_log_in": [
      null,
      "Ouvrir une session"
    ],
    "t_lowest": [
      null,
      "Le plus bas"
    ],
    "t_lowest_price": [
      null,
      "Prix le plus bas"
    ],
    "t_newegg_price": [
      null,
      "Prix Newegg"
    ],
    "t_not_in_stock": [
      null,
      "Pas en stock"
    ],
    "t_ok": [
      null,
      "OK"
    ],
    "t_please_choose_at_least_one_price_type": [
      null,
      "Sélectionnez au moins un type de prix."
    ],
    "t_please_choose_least_one_wishlist_already_imported": [
      null,
      "Sélectionnez au moins une liste d'envies que vous n'avez pas encore importée."
    ],
    "t_please_enter_a_valid_number": [
      null,
      "Veuillez saisir un numéro valide"
    ],
    "t_please_enter_a_valid_relative_value": [
      null,
      "Veuillez saisir une valeur relative valide"
    ],
    "t_please_enter_a_watch_price_below_the_current_price": [
      null,
      "Veuillez saisir un prix de suivi en dessous du prix actuel"
    ],
    "t_please_enter_your_email_address": [
      null,
      "Veuillez saisir votre adresse e-mail"
    ],
    "t_please_sign_in_to_amazon_first": [
      null,
      "Connectez-vous à Amazon d'abord."
    ],
    "t_price_type": [
      null,
      "Type de prix"
    ],
    "t_price_types": [
      null,
      "Types de prix"
    ],
    "t_prices_are_set_relative_selected_price_measure_cur": [
      null,
      "Les prix sont définis à partir de la mesure de prix sélectionnée et dans la monnaie associée au lieu du produit suivi. Sélectionnez « Prix fixe » si vous souhaitez définir le prix souhaité de tous les nouveaux suivis de prix avec la valeur indiquée."
    ],
    "t_product_data_downloaded_loading_chart_image": [
      null,
      "Informations du produit téléchargées, chargement du graphique..."
    ],
    "t_product_not_found_we_will_attempt_to_find_it_and_add_it_to_our_database_so_please_check_again_later": [
      null,
      "Produit introuvable. Nous essaierons de le trouver et de l'ajouter à notre base de données, réessayez plus tard."
    ],
    "t_products_on_this_page": [
      null,
      "Produits sur cette page"
    ],
    "t_remove_extreme_values": [
      null,
      "Supprimer les valeurs extrêmes"
    ],
    "t_sale_price": [
      null,
      "Prix de vente"
    ],
    "t_saving": [
      null,
      "Enregistrement..."
    ],
    "t_service_temporarily_unavailable": [
      null,
      "Service temporairement indisponible"
    ],
    "t_set_desired_price": [
      null,
      "Définir le prix souhaité"
    ],
    "t_set_the_desired_price_to_the": [
      null,
      "Définir le prix souhaité avec"
    ],
    "t_sign_up": [
      null,
      "S'inscrire"
    ],
    "t_signed_in_as": [
      null,
      "Se connecter en tant que %{username}"
    ],
    "t_sorry_we_couldn_t_find_your_wishlists_please_make": [
      null,
      "Désolés, nous n'avons pas pu trouver vos listes d'envies. Assurez-vous que vous êtes bien connecté(e) à Amazon et réessayez."
    ],
    "t_static_price": [
      null,
      "Prix fixe"
    ],
    "t_there_was_an_error_changing_privacy_your_wishlist": [
      null,
      "Une erreur est survenue au cours de la modification de la confidentialité de votre liste d'envies."
    ],
    "t_there_was_an_error_deleting_your_imported_wishlist": [
      null,
      "Une erreur est survenue au cours de la suppression de votre liste d'envies importée."
    ],
    "t_there_was_an_error_importing_your_wishlists": [
      null,
      "Une erreur est survenue au cours de l'importation de vos listes d'envies"
    ],
    "t_there_was_an_error_saving_your_price_watches": [
      null,
      "Une erreur est survenue au cours de l'enregistrement de vos suivis de prix"
    ],
    "t_this_is_because_it_is_either_not_a_supported_retailer_site_or_because_this_page_uses_https": [
      null,
      "Soit le site de ce vendeur n'est pas supporté soit cette page utilise HTTPS."
    ],
    "t_this_site_or_page_is_not_supported_by_the_camelizer": [
      null,
      "Ce site ou cette page n'est pas supporté(e) par The Camelizer."
    ],
    "t_update_price_watch": [
      null,
      "Mettre à jour le suivi de prix"
    ],
    "t_update_price_watches": [
      null,
      "Mettre à jour les suivis de prix"
    ],
    "t_view_all_data": [
      null,
      "Consulter toutes les informations"
    ],
    "t_view_data_for_the_last_3_months": [
      null,
      "Consulter les informations des 3 derniers mois"
    ],
    "t_view_data_for_the_last_6_months": [
      null,
      "Consulter les informations des 6 derniers mois"
    ],
    "t_view_data_for_the_last_month": [
      null,
      "Consulter les informations du dernier mois"
    ],
    "t_view_data_for_the_last_year": [
      null,
      "Consulter les informations de l'année écoulée"
    ],
    "t_view_product_on_3camels": [
      null,
      "Consulter le produit sur 3Camels"
    ],
    "t_view_product_on_retailer": [
      null,
      "Consulter le produit chez %{retailer}"
    ],
    "t_we_re_not_tracking_but_will_be_soon": [
      null,
      "Nous suivrons prochainement :"
    ],
    "t_wishlist_note": [
      null,
      "Pour être synchronisée votre liste d'envies doit être partagée ou publique"
    ],
    "t_wishlist_private": [
      null,
      "Privé"
    ],
    "t_wishlist_public": [
      null,
      "Publique"
    ],
    "t_wishlist_shared": [
      null,
      "Partagée"
    ],
    "t_wishlists": [
      null,
      "Listes d'envies"
    ],
    "t_you_need_to_choose_a_product_from_a_href_the_list_of_products_on_this_page_a": [
      null,
      "Vous devez sélectionner un produit de la liste de produits de cette page."
    ],
    "t_your_wishlist_has_been_queued_processing_we_ll_not": [
      null,
      "Votre liste d'envies a été mise en attente de traitement. Nous vous avertirons une fois le traitement achevé."
    ],
    "t_your_wishlists_have_been_queued_for_processing": [
      null,
      "Vos listes d'envies ont été mises en attente de traitement."
    ],
    "title": [
      null,
      "Le Camelizer - Outil de suivi de prix Amazon"
    ],
    "": {
      "domain": "fr",
      "lang": "fr",
      "plural-forms": "nplurals=2; plural=(n != 1);"
    }
  },
  "it": {
    "camel_icon_tip": [
      null,
      "Versione il Camelizer %{version_number} - Fai clic sull'icona per segnalare problemi o suggerire nuove funzioni."
    ],
    "products_heading": [
      null,
      "Prodotti in questa pagina. Fai clic su un link per vedere la cronologia prezzo."
    ],
    "t_1m": [
      null,
      "1m"
    ],
    "t_1y": [
      null,
      "1a"
    ],
    "t_3m": [
      null,
      "3m"
    ],
    "t_3rd_party_new": [
      null,
      "Nuovo di terzi"
    ],
    "t_3rd_party_used": [
      null,
      "Usato di terzi"
    ],
    "t_6m": [
      null,
      "6m"
    ],
    "t_add_wishlist": [
      null,
      "Aggiungi Lista desideri"
    ],
    "t_add_wishlists": [
      null,
      "Aggiungi liste desideri"
    ],
    "t_add_your_amazon_wishlist_to_your_camel_account": [
      null,
      "Aggiungi la tua Lista desideri Amazon al tuo account Camel e noi ci occuperemo di sincronizzare periodicamente la tua lista desideri con l'elenco di monitoraggi prezzo, creando nuovi monitoraggi prezzo e contrassegnando quelli esistenti, quando necessario, come acquistati."
    ],
    "t_all": [
      null,
      "tutto"
    ],
    "t_amazon": [
      null,
      "Amazon"
    ],
    "t_amazon_price_discount": [
      null,
      "Sconto prezzo Amazon"
    ],
    "t_an_error_has_occurred": [
      null,
      "Si è verificato un errore."
    ],
    "t_are_you_sure_you_want_to_delete_this_price_watch": [
      null,
      "Sei sicuro di voler eliminare questo monitoraggio prezzo?"
    ],
    "t_camelcamelcamel_users_don_t_enter_their_email_addr": [
      null,
      "Gli utenti CamelCamelCamel non devono inserire i propri indirizzi e-mail."
    ],
    "t_cancel": [
      null,
      "Cancella"
    ],
    "t_chart": [
      null,
      "Grafico"
    ],
    "t_chart_options": [
      null,
      "Opzioni grafico"
    ],
    "t_close_up_view": [
      null,
      "Vista ingrandita"
    ],
    "t_create_a_wishlist_and_then_you_can_import_it": [
      null,
      "Crea una lista desideri e poi potrai importarla."
    ],
    "t_create_price_watch": [
      null,
      "Crea monitoraggio prezzo"
    ],
    "t_create_price_watches": [
      null,
      "Crea monitoraggi prezzo"
    ],
    "t_create_price_watches_these_price_types_please_choo": [
      null,
      "Crea monitoraggi prezzo per questi tipi di prezzo (selezionane almeno uno):"
    ],
    "t_current": [
      null,
      "Attuale"
    ],
    "t_current_price": [
      null,
      "Prezzo attuale"
    ],
    "t_date_range": [
      null,
      "Intervallo date"
    ],
    "t_delete": [
      null,
      "elimina"
    ],
    "t_desired": [
      null,
      "Desiderato"
    ],
    "t_desired_price": [
      null,
      "Prezzo desiderato"
    ],
    "t_edit": [
      null,
      "Modifica"
    ],
    "t_email_address": [
      null,
      "Indirizzo e-mail:"
    ],
    "t_enter_your_desired_prices_we_ll_notify_when_they_a": [
      null,
      "Inserisci i tuoi prezzi desiderati e noi ti avviseremo quando saranno raggiunti"
    ],
    "t_helpful_links": [
      null,
      "Link utili"
    ],
    "t_highest": [
      null,
      "Il più alto"
    ],
    "t_it_looks_like_you_don_t_have_any_amazon_wishlists": [
      null,
      "Sembra che tu non abbia alcuna lista desideri Amazon"
    ],
    "t_item": [
      null,
      "1 articolo"
    ],
    "t_items": [
      null,
      "%{count} articoli"
    ],
    "t_loading": [
      null,
      "Caricamento..."
    ],
    "t_log_in": [
      null,
      "Accedi"
    ],
    "t_lowest": [
      null,
      "Il più basso"
    ],
    "t_lowest_price": [
      null,
      "Il prezzo più basso"
    ],
    "t_newegg_price": [
      null,
      "Prezzo Newegg"
    ],
    "t_not_in_stock": [
      null,
      "Non in stock"
    ],
    "t_ok": [
      null,
      "OK"
    ],
    "t_please_choose_at_least_one_price_type": [
      null,
      "Seleziona almeno un tipo di prezzo."
    ],
    "t_please_choose_least_one_wishlist_already_imported": [
      null,
      "Seleziona almeno una lista desideri che non hai ancora importato."
    ],
    "t_please_enter_a_valid_number": [
      null,
      "Inserisci un numero valido"
    ],
    "t_please_enter_a_valid_relative_value": [
      null,
      "Introduci un valore relativo valido"
    ],
    "t_please_enter_a_watch_price_below_the_current_price": [
      null,
      "Inserisci un prezzo monitorato al di sotto del prezzo attuale"
    ],
    "t_please_enter_your_email_address": [
      null,
      "Inserisci il tuo indirizzo e-mail"
    ],
    "t_please_sign_in_to_amazon_first": [
      null,
      "Prima effettua l'accesso ad Amazon."
    ],
    "t_price_type": [
      null,
      "Tipo di prezzo"
    ],
    "t_price_types": [
      null,
      "Tipi di prezzo"
    ],
    "t_prices_are_set_relative_selected_price_measure_cur": [
      null,
      "I prezzi sono impostati in relazione alla misura del prezzo selezionato e nella valuta associata alla configurazione locale del prodotto seguito. Seleziona \"prezzo statico\" se preferisci impostare il prezzo desiderato di tutti i nuovi monitoraggi prezzo su una specifica valuta."
    ],
    "t_product_data_downloaded_loading_chart_image": [
      null,
      "Dati del prodotto scaricati, caricamento immagine grafico..."
    ],
    "t_product_not_found_we_will_attempt_to_find_it_and_add_it_to_our_database_so_please_check_again_later": [
      null,
      "Prodotto non trovato. Cercheremo di trovarlo e aggiungerlo al nostro database, quindi prova a dare un'occhiata più avanti."
    ],
    "t_products_on_this_page": [
      null,
      "Prodotti di questa pagina"
    ],
    "t_remove_extreme_values": [
      null,
      "Togli valori estremi"
    ],
    "t_sale_price": [
      null,
      "Prezzo di vendita"
    ],
    "t_saving": [
      null,
      "Salvataggio..."
    ],
    "t_service_temporarily_unavailable": [
      null,
      "Servizio temporalmente non disponibile"
    ],
    "t_set_desired_price": [
      null,
      "Imposta prezzo desiderato"
    ],
    "t_set_the_desired_price_to_the": [
      null,
      "Imposta il prezzo desiderato su"
    ],
    "t_sign_up": [
      null,
      "Registrati"
    ],
    "t_signed_in_as": [
      null,
      "Registrato come %{username}"
    ],
    "t_sorry_we_couldn_t_find_your_wishlists_please_make": [
      null,
      "Siamo spiacenti, non abbiamo trovato le tue liste desideri. Verifica di essere iscritto ad Amazon e riprova."
    ],
    "t_static_price": [
      null,
      "Prezzo statico"
    ],
    "t_there_was_an_error_changing_privacy_your_wishlist": [
      null,
      "Si è verificato un errore nel modificare le impostazioni di privacy della tua lista desideri."
    ],
    "t_there_was_an_error_deleting_your_imported_wishlist": [
      null,
      "Si è verificato un errore durante l'eliminazione della tua lista desideri importata."
    ],
    "t_there_was_an_error_importing_your_wishlists": [
      null,
      "Si è verificato un errore durante l'importazione delle tue liste desideri"
    ],
    "t_there_was_an_error_saving_your_price_watches": [
      null,
      "Si è verificato un errore durante il salvataggio dei tuoi monitoraggi prezzo"
    ],
    "t_this_is_because_it_is_either_not_a_supported_retailer_site_or_because_this_page_uses_https": [
      null,
      "Questo può essere perché il sito del rivenditore non è contemplato oppure perché questa pagina utilizza HTTPS."
    ],
    "t_this_site_or_page_is_not_supported_by_the_camelizer": [
      null,
      "Questo sito o pagina non è compatibile con il Camelizer."
    ],
    "t_update_price_watch": [
      null,
      "Aggiorna monitoraggio prezzo"
    ],
    "t_update_price_watches": [
      null,
      "Aggiorna monitoraggi prezzo"
    ],
    "t_view_all_data": [
      null,
      "Vedi tutti i dati"
    ],
    "t_view_data_for_the_last_3_months": [
      null,
      "Vedi dati degli ultimi 3 mesi"
    ],
    "t_view_data_for_the_last_6_months": [
      null,
      "Vedi dati degli ultimi 6 mesi"
    ],
    "t_view_data_for_the_last_month": [
      null,
      "Vedi dati dell'ultimo mese"
    ],
    "t_view_data_for_the_last_year": [
      null,
      "Vedi dati dell'ultimo anno"
    ],
    "t_view_product_on_3camels": [
      null,
      "Vedi prodotto su 3Camels"
    ],
    "t_view_product_on_retailer": [
      null,
      "Vedi prodotto su %{retailer}"
    ],
    "t_we_re_not_tracking_but_will_be_soon": [
      null,
      "Non stiamo ancora monitorando, ma lo faremo presto:"
    ],
    "t_wishlist_note": [
      null,
      "Per poter essere sincronizzata, la tua lista desideri deve essere condivisa o pubblica."
    ],
    "t_wishlist_private": [
      null,
      "Privato"
    ],
    "t_wishlist_public": [
      null,
      "Pubblico"
    ],
    "t_wishlist_shared": [
      null,
      "Condiviso"
    ],
    "t_wishlists": [
      null,
      "Liste desideri"
    ],
    "t_you_need_to_choose_a_product_from_a_href_the_list_of_products_on_this_page_a": [
      null,
      "Devi selezionare un prodotto dalla lista prodotti di questa pagina."
    ],
    "t_your_wishlist_has_been_queued_processing_we_ll_not": [
      null,
      "La tua lista desideri è in attesa di elaborazione. Ti avviseremo al termine dell'operazione."
    ],
    "t_your_wishlists_have_been_queued_for_processing": [
      null,
      "Le tue liste desideri sono in attesa di elaborazione."
    ],
    "title": [
      null,
      "Il Camelizer - Il seguiprezzo Amazon"
    ],
    "": {
      "domain": "it",
      "lang": "it",
      "plural-forms": "nplurals=2; plural=(n != 1);"
    }
  }
};
