#! /bin/sh

if [[ $(hostname) == 'athena' ]]; then
    bspc monitor HDMI2 -d I II III IV V
    bspc monitor HDMI1 -d VI VII VIII IX X
elif [[ $(hostname) == 'aphrodite' ]]; then
    bspc monitor LVDS1 -d I II III IV V
    multimon
fi


bspc config border_width         3
bspc config window_gap          12

bspc config click_to_focus true
bspc config pointer_follows_monitor       true
bspc config pointer_modifier              mod1
bspc node pointer -f

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_unplugged_monitors true

bspc desktop -f ^1

bspc config focused_border_color "#f441af"

# ------------------------------- RULES ---------------------------------------
bspc rule -a Termite:termite desktop="^6"
bspc rule -a Google-chrome:google-chrome desktop="^7"
bspc rule -a Zathura:zathura desktop="^8" state=tiled
bspc rule -a scratchpad state=floating sticky=on hidden=on
bspc rule -a Pinentry:pinentry state=floating
bspc rule -a Vlc:vlc desktop="^5" follow=true
bspc rule -a Google-chrome:crx_cnciopoikihiagdjbjpnocolokfelagl desktop="^5" follow=true  # Videostream
bspc rule -a Soffice state=tiled desktop="^10" follow=true  # libreoffice starts with this class
bspc rule -a libreoffice state=tiled desktop="^10" follow=true
bspc rule -a Eclipse desktop="^10" follow=true

# Compton
compton -b --config .config/compton.conf

# strace -f /usr/local/bin/panel-init &> /home/bryan/panel-init.log
/usr/local/bin/panel-init

# Set Background
python3 ~/Dropbox/scripts/python/holidaybg.py
if [[ $? -ne 0 ]]; then
    landscape_bg_img=$(find ~/Dropbox/photos/backgrounds/random -type f | shuf -n 1)
fi
background $landscape_bg_img
