#!/bin/bash -ex

case "${PACKAGE_MANAGER}" in
    apt )
        sudo apt-get install -y libpng-dev libfreetype-dev pkg-config
        ;;
    yum )
        sudo yum install -y libpng-devel freetype-devel pkgconfig
        ;;
    brew )
        brew install libpng freetype pkg-config
        ;;
    none )
        # ATTOW, the 'pr-dev-1' server has all matplotlib deps installed except for libpng.
        wget http://deb.debian.org/debian/pool/main/libp/libpng1.6/libpng1.6_1.6.37.orig.tar.gz
        tar xzvf libpng1.6_1.6.37.orig.tar.gz
        cd libpng-1.6.37 || exit 1
        ./configure --prefix="${PREFIX}"
        make -j 10 && make install
        ;;
esac
