#!/bin/bash -ex

case "${PACKAGE_MANAGER}" in
    apt )
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev
        ;;
    yum )
        sudo yum install -y openssl-devel
        ;;
    brew )
        brew install openssl
        ;;
esac
