'use strict';var kn=function(){if(!Zb)return!1;try{return new ActiveXObject("MSXML2.DOMDocument"),!0}catch(a){return!1}};Zb&&kn();var ln=function(a,b){Qc.call(this);this.QS=a||0;this.Rl=b||10;if(this.QS>this.Rl)throw Error("[goog.structs.Pool] Min can not be greater than max");this.ad=new El;this.Hj=new Ee;this.MB=0;this.HE=null;this.vu()};v(ln,Qc);d=ln.prototype;d.getObject=function(){var a=u();if(!(null!=this.HE&&a-this.HE<this.MB)){var b=this.Nfa();b&&(this.HE=a,this.Hj.add(b));return b}};d.um=function(a){return this.Hj.remove(a)?(this.AA(a),!0):!1};
d.Nfa=function(){for(var a;0<this.kO()&&(a=this.ad.Xk(),!this.yF(a));)this.vu();!a&&this.ma()<this.Rl&&(a=this.Ph());return a};d.AA=function(a){this.Hj.remove(a);this.yF(a)&&this.ma()<this.Rl?this.ad.enqueue(a):this.Yk(a)};d.vu=function(){for(var a=this.ad;this.ma()<this.QS;)a.enqueue(this.Ph());for(;this.ma()>this.Rl&&0<this.kO();)this.Yk(a.Xk())};d.Ph=function(){return{}};d.Yk=function(a){if("function"==typeof a.fb)a.fb();else for(var b in a)a[b]=null};
d.yF=function(a){return"function"==typeof a.M1?a.M1():!0};d.contains=function(a){return this.ad.contains(a)||this.Hj.contains(a)};d.ma=function(){return this.ad.ma()+this.Hj.ma()};d.y6=function(){return this.Hj.ma()};d.kO=function(){return this.ad.ma()};d.Ec=function(){return this.ad.Ec()&&this.Hj.Ec()};d.aa=function(){ln.W.aa.call(this);if(0<this.y6())throw Error("[goog.structs.Pool] Objects not released");delete this.Hj;for(var a=this.ad;!a.Ec();)this.Yk(a.Xk());delete this.ad};var mn=function(a,b){this.eh=a;this.Qe=b};mn.prototype.getKey=function(){return this.eh};mn.prototype.bc=function(){return this.Qe};mn.prototype.clone=function(){return new mn(this.eh,this.Qe)};var nn=function(a){this.rf=[];a&&this.d$(a)};d=nn.prototype;d.insert=function(a,b){var c=this.rf;c.push(new mn(a,b));this.eba(c.length-1)};d.d$=function(a){var b;if(a instanceof nn){if(b=a.xb(),a=a.T(),0>=this.ma()){for(var c=this.rf,e=0;e<b.length;e++)c.push(new mn(b[e],a[e]));return}}else b=Eb(a),a=Db(a);for(e=0;e<b.length;e++)this.insert(b[e],a[e])};d.remove=function(){var a=this.rf,b=a.length,c=a[0];if(!(0>=b))return 1==b?ib(a):(a[0]=a.pop(),this.dba(0)),c.bc()};
d.dba=function(a){for(var b=this.rf,c=b.length,e=b[a];a<c>>1;){var f=this.F6(a),h=this.K7(a),f=h<c&&b[h].getKey()<b[f].getKey()?h:f;if(b[f].getKey()>e.getKey())break;b[a]=b[f];a=f}b[a]=e};d.eba=function(a){for(var b=this.rf,c=b[a];0<a;){var e=this.e7(a);if(b[e].getKey()>c.getKey())b[a]=b[e],a=e;else break}b[a]=c};d.F6=function(a){return 2*a+1};d.K7=function(a){return 2*a+2};d.e7=function(a){return a-1>>1};d.T=function(){for(var a=this.rf,b=[],c=a.length,e=0;e<c;e++)b.push(a[e].bc());return b};
d.xb=function(){for(var a=this.rf,b=[],c=a.length,e=0;e<c;e++)b.push(a[e].getKey());return b};d.Kn=function(a){return bb(this.rf,function(b){return b.bc()==a})};d.Wa=function(a){return bb(this.rf,function(b){return b.getKey()==a})};d.clone=function(){return new nn(this)};d.ma=function(){return this.rf.length};d.Ec=function(){return hb(this.rf)};d.clear=function(){ib(this.rf)};var on=function(){nn.call(this)};v(on,nn);on.prototype.enqueue=function(a,b){this.insert(a,b)};on.prototype.Xk=function(){return this.remove()};var pn=function(a,b){this.XL=void 0;this.gy=new on;ln.call(this,a,b)};v(pn,ln);d=pn.prototype;d.getObject=function(a,b){if(!a)return(a=pn.W.getObject.call(this))&&this.MB&&(this.XL=g.setTimeout(t(this.ww,this),this.MB)),a;this.gy.enqueue(l(b)?b:100,a);this.ww()};d.ww=function(){for(var a=this.gy;0<a.ma();){var b=this.getObject();if(b)a.Xk().apply(this,[b]);else break}};d.AA=function(a){pn.W.AA.call(this,a);this.ww()};d.vu=function(){pn.W.vu.call(this);this.ww()};
d.aa=function(){pn.W.aa.call(this);g.clearTimeout(this.XL);this.gy.clear();this.gy=null};var qn=function(a,b,c,e){this.cc=a;this.Xi=!!e;pn.call(this,b,c)};v(qn,pn);qn.prototype.Ph=function(){var a=new Kf,b=this.cc;b&&b.forEach(function(b,e){a.headers.set(e,b)});this.Xi&&a.ez(!0);return a};qn.prototype.yF=function(a){return!a.isDisposed()&&!a.Zf()};var rn=function(a,b,c,e,f,h){F.call(this);this.vd=l(a)?a:1;this.Ti=l(f)?Math.max(0,f):0;this.Xi=!!h;this.hq=new qn(b,c,e,h);this.Ic=new H;this.Pa=new Cl(this)};v(rn,F);var sn="ready complete success error abort timeout".split(" ");d=rn.prototype;d.zt=function(a){this.Ti=Math.max(0,a)};
d.send=function(a,b,c,e,f,h,k,n,q,z){if(this.Ic.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new tn(b,t(this.L8,this,a),c,e,f,k,l(n)?n:this.vd,q,l(z)?z:this.Xi);this.Ic.set(a,b);a=t(this.A8,this,a);this.hq.getObject(a,h);return b};d.abort=function(a,b){var c=this.Ic.get(a);if(c){var e=c.gA;c.Eha(!0);b&&(e&&(this.NU(e,c.oJ),rd(e,"ready",function(){this.hq.um(e)},!1,this)),this.Ic.remove(a));e&&e.abort()}};
d.A8=function(a,b){var c=this.Ic.get(a);c&&!c.gA?(this.y0(b,c.oJ),b.zt(this.Ti),b.WH(c.jk),b.ez(c.Xi),c.gA=b,this.dispatchEvent(new un("ready",this,a,b)),this.aV(a,b),c.QJ&&b.abort()):this.hq.um(b)};d.L8=function(a,b){var c=b.target;switch(b.type){case "ready":this.aV(a,c);break;case "complete":return this.G8(a,c,b);case "success":this.z9(a,c);break;case "timeout":case "error":this.ah(a,c);break;case "abort":this.y8(a,c)}return null};
d.aV=function(a,b){var c=this.Ic.get(a);!c||c.tL||c.pE()?(c&&(this.NU(b,c.oJ),this.Ic.remove(a)),this.hq.um(b)):(c.T9(),b.send(c.getUrl(),c.Xaa,c.lc,c.kl()))};d.G8=function(a,b,c){var e=this.Ic.get(a);if(7==b.Kj||b.Od()||e.pE())if(this.dispatchEvent(new un("complete",this,a,b)),e&&(e.jia(!0),e.sL))return e.sL.call(b,c);return null};d.y8=function(a,b){this.dispatchEvent(new un("abort",this,a,b))};d.z9=function(a,b){this.dispatchEvent(new un("success",this,a,b))};
d.ah=function(a,b){this.Ic.get(a).pE()&&this.dispatchEvent(new un("error",this,a,b))};d.NU=function(a,b,c){this.Pa.Hd(a,c||sn,b)};d.y0=function(a,b,c){this.Pa.listen(a,c||sn,b)};d.aa=function(){rn.W.aa.call(this);this.hq.fb();this.hq=null;this.Pa.fb();this.Pa=null;this.Ic.clear();this.Ic=null};var un=function(a,b,c,e){E.call(this,a,b);this.id=c;this.gA=e};v(un,E);
var tn=function(a,b,c,e,f,h,k,n,q){this.du=a;this.Xaa=c||"GET";this.lc=e;this.cc=f||null;this.vd=l(k)?k:1;this.xK=0;this.QJ=this.tL=!1;this.oJ=b;this.sL=h;this.jk=n||"";this.Xi=!!q;this.gA=null};d=tn.prototype;d.getUrl=function(){return this.du};d.kl=function(){return this.cc};d.Ug=function(){return this.vd};d.T9=function(){this.xK++};d.pE=function(){return this.xK>this.vd};d.jia=function(a){this.tL=a};d.Eha=function(a){this.QJ=a};var vn=function(){this.name="unknown";this.state="error";this.h$=null;this.allowStop=!0;this.nh=null;this.extraData={}},wn=function(a,b){this.iZ=a;this.Eh=b;this.Pga=!!b&&"running"==b.state},zn=function(a,b,c){void 0===b&&(xn||(xn=new rn(3,null,1,10,2E3)),b=xn);void 0===c&&(yn||(yn=new rn(0,null,1,10,15E3)),c=yn);this.sg=a;this.gq=b;this.iq=[];this.jZ=c;this.a=D("mr.dial.Client")};d=zn.prototype;d.abort=function(){var a=this;this.iq.forEach(function(b){a.gq.abort(b,!0);a.jZ.abort(b,!0)})};
d.launchApp=function(a,b){var c=new Ec,e=(++An).toString();this.iq.push(e);this.jZ.send(e,this.qC(a),"POST",b,null,0,this.JM("launchApp","POST",e,c));return c.promise};d.AX=function(a){var b=new Ec,c=(++An).toString();this.iq.push(c);this.gq.send(c,this.qC(a),"DELETE",null,null,0,this.JM("stopApp","DELETE",c,b),0);return b.promise};d.oC=function(a){var b=this;return new Promise(function(c){var e=(++An).toString();b.iq.push(e);b.gq.send(e,b.qC(a),"GET",null,null,0,t(b.Wba,b,e,c))})};
d.Wba=function(a,b,c){nb(this.iq,a);a=c.target;He(this.a,"GetAppInfo","GET",a,!0);if(a.Od())if(c=(c=a.ff())?Ie(c):null){var e=c.getElementsByTagName("service");if(e&&1==e.length){c=new vn;for(var f=0,h=e[0].childNodes.length;f<h;f++){var k=e[0].childNodes[f];if("state"==k.nodeName){a:switch(k.textContent){case "running":k="running";break a;case "stopped":k="stopped";break a;default:k="error"}c.state=k}else"name"==k.nodeName?c.name=k.textContent:"link"==k.nodeName?c.nh=k.getAttribute("href"):"options"==
k.nodeName?c.allowStop="false"!=k.getAttribute("allowStop"):c.extraData[k.nodeName]=k.innerHTML}if("unknown"==c.name)this.a.info("GET response missing name value"),b(new wn(a,null));else if("error"==c.state)this.a.info("GET response missing state value"),b(new wn(a,null));else{if((e=/installable=(.+)/.exec(c.state))&&e[1])c.state="installable",c.h$=e[1];else if("running"!=c.state&&"stopped"!=c.state){this.a.info("GET response has invalid state value");b(new wn(a,null));return}b(new wn(a,c))}}else this.a.info("Invalid GET response (invalid service)"),
b(new wn(a,null))}else this.a.info("Invalid or empty response"),b(new wn(a,null));else this.a.info("Request to "+a.hw()+" failed"),b(new wn(a,null))};d.qC=function(a){var b=this.sg.qj;"/"!=b.charAt(b.length-1)&&(b+="/");return b+a};d.JM=function(a,b,c,e){var f=this;return function(h){nb(f.iq,c);h=h.target;He(f.a,a,b,h,!0);h.Od()?e.resolve(void 0):e.reject(Error(hf(h.Kj)))}};var xn=null,yn=null,An=999;var Bn=function(a,b,c){this.appName=b;this.launchParameter=void 0===c?"":c},Dn=function(a){if(a.startsWith("urn:dial-multiscreen-org:dial:application:")){var b=a.indexOf("?"),c=a.substring(42,0<b?b:void 0);a=c&&0<c.length?new Bn(a,c,0<b?a.substring(b+1):void 0):null}else a=Cn(a);return a},Cn=function(a){var b=(new Vj(a)).gl;if(!b)return null;var c=En.exec(b),c=c?c[1]:null;if(!c)return null;c=decodeURIComponent(c);if(b=(b=Fn.exec(b))?b[1]:void 0)try{b=Ki(b)}catch(e){return Gn.u("Invalid base64 encoded postData:"+
b),null}return new Bn(a,c,b)},Gn=D("mr.dial.MediaSource"),En=/__dialAppName__=([A-Za-z0-9-._~!$&'()*+,;=%]+)/,Fn=/__dialPostData__=([A-Za-z0-9]+={0,2})/;var Hn=function(a,b){this.Gb=a;this.appName=b};var In=function(a){this.He=new Map;this.xA=a};d=In.prototype;d.init=function(){Wh(this)};d.clear=function(){this.He.clear()};d.add=function(a){this.rN(a.Gb.id)||(this.He.set(a.Gb.id,a),this.xA.mba(a))};d.rN=function(a){return this.He.get(a)||null};d.sN=function(a){for(var b=ia(this.He),c=b.next();!c.done;c=b.next())if(c=ia(c.value),c.next(),c=c.next().value,c.Gb.sinkId==a)return c;return null};d.Kfa=function(a){if(a=this.sN(a))this.He.delete(a.Gb.id),this.xA.hT(a)};
d.JU=function(a){var b=this.He.get(a);b&&(this.He.delete(a),this.xA.hT(b))};d.li=function(){return Array.from(this.He.values(),function(a){return a.Gb})};d.Y4=function(){return Array.from(this.He.values())};d.Ca=function(){return"dial.ActivityRecords"};d.getData=function(){return[Array.from(this.He)]};d.tb=function(){var a=Th(this);a&&(this.He=new Map(a))};var Jn={Epa:0,qsa:1,ora:2,Dpa:3},Kn={ERROR:0,Hra:1,EMPTY:2},Ln=function(a){gh("MediaRouter.Dial.Create.Route",a,Jn)},Mn=function(a){gh("MediaRouter.Dial.Device.Description.Failure",a,Kn)};var Nn=/^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/,On=[4278190080,4293918720,4294901760],Pn=[167772160,2886729728,3232235520],Qn=function(a){var b=document.createElement("a");b.href=a;return b};var Rn=function(){this.configId=this.modelName=this.deviceType=this.expireTimeMillis=this.fetchTimeMillis=this.appUrl=this.ipAddress=this.friendlyName=this.deviceLabel=this.uniqueId=null};
Rn.prototype.Rz=function(){var a;if(this.deviceLabel)if(this.uniqueId)if(this.friendlyName)if(this.ipAddress)if(this.appUrl)if(this.fetchTimeMillis)if(this.expireTimeMillis){a=this.ipAddress;var b=Qn(this.appUrl);a="http:"==b.protocol&&b.hostname==a?null:"Invalid appUrl"}else a="Missing expireTimeMillis";else a="Missing fetchTimeMillis";else a="Missing appUrl";else a="Missing ipAddress";else a="Missing friendlyName";else a="Missing uniqueId";else a="Missing deviceLabel";return a};
Rn.prototype.toString=function(){return JSON.stringify(this,function(a,b){return p(b)&&0==b.indexOf("uuid:")?"***":b})};
var Sn=function(a){var b=new Rn;b.uniqueId=a.uniqueId;b.deviceLabel=a.deviceLabel;b.friendlyName=a.friendlyName;b.ipAddress=a.ipAddress;b.appUrl=a.appUrl;b.fetchTimeMillis=a.fetchTimeMillis;b.expireTimeMillis=a.expireTimeMillis;b.deviceType=a.deviceType;b.modelName=a.modelName;b.configId=a.configId;return b},Vn=function(a){this.yq=new Map;this.uc=new Map;this.iG=new Map;var b;(b=a)||(Tn||(Tn=new rn(3,null,1,10,2E3)),b=Tn);this.gq=b;a||(Un||(Un=new rn(2,null,1,10,3E3)),a=Un);this.S_=a;this.a=D("mr.dial.DeviceDescriptionService");
Wh(this)};d=Vn.prototype;d.Ca=function(){return"mr.dial.DeviceDescriptionService"};d.getData=function(){return[Array.from(this.yq)]};d.tb=function(){var a=Th(this);if(a)for(var a=ia(a),b=a.next();!b.done;b=a.next()){var c=ia(b.value),b=c.next().value,c=c.next().value;null!=Sn(c).Rz()?this.a.error("Dropping invalid description "+b+" loaded from storage."):this.yq.set(b,Sn(c))}};d.b6=function(a){var b=this.Z1(a);return b?(fh("MediaRouter.Dial.Device.Description.Cached"),Promise.resolve(b)):this.w4(a)};
d.R_=function(a){var b=this.uc.get(a);b&&(this.gq.abort(a,!0),b.Pb.reject(Error("Aborted")))};d.Z1=function(a){var b=this.yq.get(a.deviceLabel);return b?b.configId!=a.configId||Date.now()>=b.expireTimeMillis?(this.a.C("Removing invalid entry "+b.toString()),this.yq.delete(a.deviceLabel),null):b:null};
d.w4=function(a){var b=this;if(!Wn(a.deviceDescriptionUrl))return Promise.reject(Error("Invalid device description URL: "+a.deviceDescriptionUrl));var c=this.uc.get(a.deviceLabel);if(c){if(c.deviceDescriptionUrl==a.deviceDescriptionUrl)return c.Pb.promise;this.R_(a.deviceLabel)}var e=new Ec,c={deviceDescriptionUrl:a.deviceDescriptionUrl,Pb:e};this.uc.set(a.deviceLabel,c);chrome.dial.fetchDeviceDescription?chrome.dial.fetchDeviceDescription(a.deviceLabel,function(c){b.uc.delete(a.deviceLabel);c?(c=
b.mU(a,c.deviceDescription,c.appUrl))?e.resolve(c):e.reject(Error("Failed to process fetch result")):e.reject(chrome.runtime.lastError&&chrome.runtime.lastError.message?Error("chrome.dial.fetchDeviceDescription failed, chrome.runtime.lastError: "+chrome.runtime.lastError.message):Error("chrome.dial.fetchDeviceDescription failed, chrome.runtime.lastError: Unknown error"))}):this.gq.send(a.deviceLabel,a.deviceDescriptionUrl,"GET",null,null,0,function(c){b.uc.delete(a.deviceLabel);(c=b.E9(a,c))?e.resolve(c):
e.reject(Error("Failed to get device description"))});return e.promise};d.E9=function(a,b){var c=b.target;He(this.a,"fetchDeviceDescription","GET",c);if(!c.Od())return this.a.info("Request to "+c.hw()+" failed"),Mn(0),null;b=c.ff();if(!b)return this.a.info("Invalid or empty response"),Mn(2),null;c=c.getResponseHeader("Application-URL");return c?this.mU(a,b,c):(this.a.info("Invalid or empty AppURL"),Mn(2),null)};
d.mU=function(a,b,c){b=this.uda(a,b,c);if(!b)return Mn(1),this.a.info("Invalid device description"),null;this.a.info("Got device description for "+b.deviceLabel);this.a.C("... device description was: "+b.toString());null!=b.configId&&(this.a.C("Caching device description for "+b.deviceLabel),this.yq.set(a.deviceLabel,b));return b};
d.uda=function(a,b,c){var e=Ie(b);if(!e)return null;var f=new Rn;f.fetchTimeMillis=Date.now();f.expireTimeMillis=f.fetchTimeMillis+18E5;f.deviceLabel=a.deviceLabel;f.configId=a.configId;a=Qn(a.deviceDescriptionUrl);f.ipAddress=a.hostname;f.deviceType=Xn(e,"deviceType");f.modelName=Xn(e,"modelName");f.friendlyName=Xn(e,"friendlyName");f.uniqueId=Xn(e,"UDN");!f.friendlyName&&f.modelName&&(f.friendlyName=f.modelName,f.uniqueId&&(f.friendlyName+="["+f.uniqueId.slice(-4)+"]"),this.a.u("Fixed device description: created friendlyName from modelName."));
f.appUrl=c;c=f.Rz();this.a.C(function(){return"Device description: "+Yn(e)});return c?(this.a.u(function(){return"Device description failed to validate: "+f},c),null):f};var Xn=function(a,b){return(a=a.getElementsByTagName(b))&&0!=a.length?a[0].textContent:null},Yn=function(a){var b=function(a){for(var b=0,c=a.length;b<c;b++)a[b].textContent="***"};b(a.getElementsByTagName("UDN"));b(a.getElementsByTagName("serialNumber"));return(new XMLSerializer).serializeToString(a)};
Vn.prototype.Bq=function(a){var b=this,c=this.iG.get(a);if(c)return c.promise;c=new Ec;this.iG.set(a,c);this.S_.send(a,a,"GET",null,null,0,function(e){b.iG.delete(a);e=e.target;He(b.a,"checkAccess","GET",e,!1);c.resolve(e.Od())});return c.promise};
var Wn=function(a){a=Qn(a);var b;if(b="http:"==a.protocol)a:{b:if((a=a.hostname.match(Nn))&&5==a.length){b=[];for(var c=0;4>c;c++)if(b[c]=Number.parseInt(a[c+1],10),0>b[c]||255<b[c]){a=null;break b}a=b}else a=null;if(a)for(a=(a[0]<<24|a[1]<<16|a[2]<<8|a[0])>>>0,b=0;3>b;b++)if((a&On[b])>>>0==Pn[b]){b=!0;break a}b=!1}return b},Tn=null,Un=null;var Zn=null,$n=null,ao=function(){Zn||(Zn=new ej(3,"dial.DialOnDeviceListEventListener","mr.dial.SinkDiscoveryService",chrome.dial.onDeviceList));$n||($n=new ej(4,"dial.DialOnErrorEventListener","mr.dial.SinkDiscoveryService",chrome.dial.onError));return[Zn,$n]};var bo=function(a,b){b=void 0===b?new Vn:b;this.Ct=a;this.bM=b;this.a=D("mr.dial.SinkDiscoveryService");this.Ed=new Map;this.xx=this.aF=!1;this.Ng={vn:0,Lo:0};this.rv=0};ja(bo,uh);d=bo.prototype;d.init=function(){Wh(this);Eh("mr.dial.SinkDiscoveryService",this)};d.start=function(){this.aF||(this.a.info("Starting..."),this.aF=!0,ao().forEach(function(a){return a.addListener()}),this.refresh())};
d.refresh=function(){var a=this;this.aF?chrome.dial.discoverNow(function(b){a.a.info("chrome.dial.discoverNow = "+b)}):this.a.info("Not started. Ignoring discover().")};
d.Rba=function(a){var b=this;this.a.info("onDeviceList returned "+a.length+" devices");this.a.C(function(){return"....the list is: "+JSON.stringify(a)});this.xx=!1;var c=0,e=[],f=new Set;a.forEach(function(a){e.push(b.zea(a).then(function(a){f.add(a.getId());b.waa(a)},function(){c++}))});kj(e).then(function(){b.xx||b.Qx(f).then(function(){var a=b.Ed.size;b.zU(a,a+c)})})};
d.zU=function(a,b){this.Ng={vn:a,Lo:b};36E5>Date.now()-this.rv||(a=this.Ng,hh("MediaRouter.Dial.AvailableDevicesCount",a.vn),hh("MediaRouter.Dial.KnownDevicesCount",a.Lo),this.rv=Date.now())};d.waa=function(a){if(!this.xx){this.a.C("mayAddSink, id = "+a.getId());var b=this.Ed.get(a.getId());b?b.update(a)&&(this.a.C("Updated sink "+b.getId()),this.Ct.Ee(b)):(this.a.C(function(){return"Adding new sink "+a.getId()+": "+a.RX()}),this.Ed.set(a.getId(),a),this.Ct.gm(a))}};
d.Qx=function(a){var b=this,c=[],e=[];this.Ed.forEach(function(f){a.has(f.getId())||e.push(b.Y1(f).then(function(a){a||(b.Ed.delete(f.getId()),c.push(f))}))});return kj(e).then(function(){0<c.length&&b.Ct.fg(c)})};d.Y1=function(a){return a.Rh?this.bM.Bq(a.Rh):Promise.resolve(!1)};
d.zea=function(a){return this.bM.b6(a).then(function(b){var c;b.uniqueId?(c=b.uniqueId,0==c.indexOf("uuid:")&&(c=c.substr(5)),c=c.replace(/-/g,"").toLowerCase()):c="";var e=b.uniqueId?Pi.ga().Zn(c):a.deviceLabel,f=co.test(b.modelName);return(new Qi(b.friendlyName,c)).Hy(e).cja(b.ipAddress).Cia(b.appUrl).Aia(a.deviceDescriptionUrl).xja(b.modelName).jX(!f)})};
d.Nca=function(a){switch(a.code){case "no_valid_network_interfaces":case "network_disconnected":this.a.u("DIAL error: "+a.code+". Clear device list now.");a=Array.from(this.Ed.values());this.Ed.clear();this.Ct.fg(a);this.zU(0,0);this.xx=!0;break;case "no_listeners":case "socket_error":case "cellular_network":case "unknown":this.a.u("DIAL error: "+a.code+". Keep device list.");break;default:this.a.u("Unhandled DIAL error: "+a.code)}};d.pa=function(a){return this.Ed.get(a)||null};
d.Y7=function(a){var b=[];this.Ed.forEach(function(c){"available"==c.Pf(a)&&b.push(c.Bj())});var c=eo[a];return new Lk(b,c?[c]:void 0)};d.gf=function(){return Array.from(this.Ed.values())};d.vba=function(a,b){this.Ct.Ee(b)};d.handleEvent=function(a,b){for(var c=[],e=1;e<arguments.length;++e)c[e-1]=arguments[e];if(a==chrome.dial.onDeviceList)this.Rba.apply(this,[].concat(ka(c)));else if(a==chrome.dial.onError)this.Nca.apply(this,[].concat(ka(c)));else throw Error("Unhandled event");};d.Ca=function(){return"dial.DialSinkDiscoveryService"};
d.getData=function(){return[new fo(Array.from(this.Ed),this.Ng),{deviceCountMetricsRecordTime:this.rv}]};d.tb=function(){var a=Th(this);if(a){for(var b=ia(a.sinks),c=b.next();!c.done;c=b.next())c=c.value,this.Ed.set(c[0],Ri(c[1]));this.Ng=a.deviceCounts}if(a=Uh(this))this.rv=a.deviceCountMetricsRecordTime};
var eo={YouTube:"https://www.youtube.com",Netflix:"https://www.netflix.com",Pandora:"https://www.pandora.com",Radio:"https://www.pandora.com",Hulu:"https://www.hulu.com",Vimeo:"https://www.vimeo.com",Dailymotion:"https://www.dailymotion.com","com.dailymotion":"https://www.dailymotion.com"},co=/Eureka Dongle|Chromecast Audio/i,fo=function(a,b){this.sinks=a;this.deviceCounts=b};var go=function(a,b){this.a=D("mr.dial.AppDiscoveryService");this.Ad=new Set;this.sa=a;this.oe=b;this.uc=new Map;this.uB=new Map;this.tg=null;this.sp=!1};d=go.prototype;d.init=function(){Wh(this)};d.start=function(){this.a.info("Starting periodic scanning.");this.sp||(this.sp=!0,this.mM())};d.stop=function(){this.a.info("Stopping periodic scanning.");this.sp&&(this.sp=!1,this.tg&&(clearTimeout(this.tg),this.tg=null),this.uc.clear(),this.uB.forEach(function(a){a.abort()}))};
d.FG=function(a){if(!this.Ad.has(a)||this.D0(a))this.Ad.add(a),0!=this.sa.Ed.size&&(this.sp?this.sa.gf().forEach(this.lM.bind(this,a)):this.start())};d.zI=function(a){this.Ad.delete(a)};d.A7=function(){return Array.from(this.Ad)};
d.mM=function(){var a=this;this.a.info("Start app status scan.");var b=[];this.sa.gf().forEach(function(c){b.push.apply(b,a.lt(c))});this.oe.Y4().forEach(function(c){b.push(a.Sga(c))});kj(b).then(function(){a.sp&&!a.tg&&(a.a.C("Scan complete; scheduling for next scan."),a.tg=setTimeout(function(){a.O3()},6E4))})};d.O3=function(){this.a.C("Start app status scan (timer-based)");this.tg=null;this.mM()};
d.lt=function(a){if(!a.Np)return[];for(var b=[],c=ia(this.Ad),e=c.next();!e.done;e=c.next())b.push(this.lM(e.value,a));return b};d.lM=function(a,b){if("unknown"!=b.Pf(a)&&36E5>Date.now()-b.e5(a)||!b.Np)return Promise.resolve();this.a.C("Querying "+b.getId()+" for "+a+" to update app status");return this.gN(b,a).then(this.Gaa.bind(this,b,a))};
d.Sga=function(a){var b=this.sa.pa(a.Gb.sinkId);if(!b)return this.a.u("Activity refers to nonexistent sink: "+a.Gb.id),Promise.resolve();if(!b.Np)return Promise.resolve();a=a.appName;this.a.C("Querying "+b.getId()+" for "+a+" to update activity");return this.gN(b,a).then(this.Faa.bind(this,b,a))};d.d6=function(a){var b=this.uB.get(a.getId());b||(b=new zn(a),this.a.C("Created DIAL client for "+a.getId()),this.uB.set(a.getId(),b));return b};
d.gN=function(a,b){var c=this,e=ho(a,b),f=this.uc.get(e);if(f)return f;f=this.d6(a).oC(b);this.uc.set(e,f);a=function(){c.uc.delete(e)};f.then(a,a);return f};d.m5=function(a,b){if(404==b.iZ.Sa())return"unavailable";b=b.Eh;if("Netflix"==a)return this.d5(b);switch(b.state){case "running":case "stopped":return"available";default:return"unavailable"}};d.d5=function(a){return!a.extraData||"websocket"!=a.extraData.capabilities||"running"!=a.state&&"stopped"!=a.state?"unavailable":"available"};
var ho=function(a,b){return a.getId()+":"+b};d=go.prototype;d.Gaa=function(a,b,c){if(404==c.iZ.Sa()||c.Eh){c=this.m5(b,c);this.a.C("Got app status "+c+" from "+a.getId()+" for "+b);var e=a.Pf(b);a.qt(b,c);c!=e&&this.sa.vba(b,a)}else this.a.u("Failed to process app availability; "+a.getId()+" does not support app availability"),a.jX(!1)};d.Faa=function(a,b,c){(a=this.oe.sN(a.getId()))&&a.appName==b&&!c.Pga&&this.oe.JU(a.Gb.id)};
d.D0=function(a){return this.sa.gf().some(function(b){return"unknown"==b.Pf(a)})};d.Ca=function(){return"dial.AppDiscoveryService"};d.getData=function(){return[this.A7()]};d.tb=function(){var a=Th(this);this.Ad=new Set(a||[])};var io=function(a,b,c){this.L=a;this.Dd=b||new bo(this);this.oe=new In(this);this.pe=c||new go(this.Dd,this.oe);this.a=D("mr.DialProvider")};d=io.prototype;d.getName=function(){return"dial"};d.Tb=function(){this.oe.init();this.Dd.init();this.Dd.start();this.pe.init();this.Cs()};d.hr=function(a){this.a.C("GetAvailableSinks for "+a);return(a=Dn(a))?this.Dd.Y7(a.appName):Mk};d.startObservingMediaSinks=function(a){if(a=Dn(a))this.pe.FG(a.appName),this.Cs()};
d.stopObservingMediaSinks=function(a){if(a=Dn(a))this.pe.zI(a.appName),this.nx()};d.startObservingMediaRoutes=function(){this.Cs()};d.stopObservingMediaRoutes=function(){this.nx()};d.nx=function(){(0==this.Dd.Ed.size||0==this.pe.Ad.size&&0==this.oe.He.size)&&this.pe.stop()};d.Cs=function(){0<this.Dd.Ed.size&&(0<this.pe.Ad.size||0<this.oe.He.size)&&this.pe.start()};d.pa=function(a){return(a=this.Dd.pa(a))?a.Bj():null};d.li=function(){return this.oe.li()};
d.createRoute=function(a,b,c,e){var f=this,h=this.Dd.pa(b);if(!h)return Ln(0),Pg(Error("Unkown sink: "+b));Pi.ga().tm=new Oi(h.xd,h.Ga);var k=Dn(a);if(!k)return Pg(Error("No app name set."));var n=k.appName,q=this.ZS(h);return Qg(q.oC(n).then(function(a){if(!a.Eh)throw Error("Failed to get app info");if("running"==a.Eh.state)return q.AX(n)}).then(function(){return q.launchApp(n,k.launchParameter)}).then(function(){return f.Dg(b,a,!0,n,c,e)}).catch(function(a){Ln(3);throw a;}))};d.joinRoute=function(){return Pg(Error("Not supported"))};
d.connectRouteByRouteId=function(){return Pg(Error("Not supported"))};d.detachRoute=function(){};d.Dg=function(a,b,c,e,f,h){Ln(1);a=ni(f,this.getName(),a,b,c,e,null);a.offTheRecord=h;this.oe.add(new Hn(a,e));return a};d.gm=function(a){this.L.onSinkAvailabilityUpdated(this,1);this.Cs();this.pe.lt(a);this.L.sf();Pi.ga().sm=new Oi(a.xd,a.Ga)};d.fg=function(a){var b=this;if(0==this.Dd.Ed.size)this.L.onSinkAvailabilityUpdated(this,0);this.nx();a.forEach(function(a){b.oe.Kfa(a.getId())});this.L.sf()};
d.Ee=function(){this.L.sf()};d.mba=function(a){this.Cs();this.L.fm(this,a.Gb)};d.hT=function(a){a=a.Gb;if(a.isLocal)this.L.onPresentationConnectionStateChanged(a.id,"terminated");this.nx();this.L.Vj(this,a)};d.terminateRoute=function(a){var b=this.oe.rN(a);if(!b)return Promise.reject(new Kk(3,"Route in DIAL provider not found for routeId "+a));this.oe.JU(a);return(a=this.Dd.pa(b.Gb.sinkId))?this.ZS(a).AX(b.appName):Promise.reject(new Kk(3,"Sink in DIAL provider not found for sinkId "+b.Gb.sinkId))};
d.qo=function(){return null};d.po=function(){return null};d.sendRouteMessage=function(){return Promise.reject(Error("DIAL sending messages is not supported"))};d.sendRouteBinaryMessage=function(){return Promise.reject(Error("DIAL sending messages is not supported"))};d.zq=function(a,b){b=this.Dd.pa(b);return!b||qh(a)?!1:(a=Dn(a))?"available"==b.Pf(a.appName):!1};d.zn=function(){return!1};d.searchSinks=function(){return null};d.ZS=function(a){return new zn(a)};var jo=function(a,b){this.U1=a;this.PB=b;this.ij=this.U1.sa;this.a=D("mr.cast.CastDialSinkDiscoveryCallbacks")};d=jo.prototype;d.R3=function(a){return this.ij.Bq(a)};d.dQ=function(a){var b=this.ij.pa(a.getId());return b?b:(a=a.Ga)?this.ij.W7(a,Pi.ga().Cn||8009):null};d.gm=function(a){this.dQ(a)?cj(2):this.eY(a);this.PB.gm(a)};d.eY=function(a){var b=this,c=Ti(a);c&&this.R3(c).then(function(e){e?b.dQ(a)?cj(2):(b.ij.qq(c),cj(0)):fh("MediaRouter.Dial.Sink.Discovered.NonCast")},na)};
d.fg=function(a){var b=this;x(a,function(a){var c=b.ij.pa(a.getId());c&&c.Rn&&b.ij.xm(a.getId())});this.PB.fg(a)};d.Ee=function(a){var b=this.ij.pa(a.getId());b?b.Rn&&(b.update(a.jo(),a.Ga,b.sb(),b.Zd)&&this.a.info("Updated Cast sink with DIAL sink: "+a.getId()),this.ij.Ee(b)):this.eY(a);this.PB.Ee(a)};var ko=function(a,b){this.sa=new bo(new jo(b,this));this.Cm=new H;this.L=a;this.pt=this.Im=0;this.qs=new Ee;this.Cb=new io(this,this.sa)};d=ko.prototype;d.Ca=function(){return"cast.DialProviderWrapper"};d.getData=function(){return[new lo(this.Cm.g(),this.Im,this.pt,this.qs.T())]};d.tb=function(){var a=Th(this);a&&(this.Cm.addAll(a.Fga),this.Im=a.sequenceNumber,this.pt=a.Dha,this.qs.addAll(a.V$))};d.getName=function(){return this.Cb.getName()};d.Tb=function(){this.Cb.Tb();Wh(this)};d.li=function(){return this.Cb.li()};
d.yT=function(){};d.hr=function(a){return this.Cb.hr(a)};d.startObservingMediaSinks=function(a){this.Cb.startObservingMediaSinks(a)};d.stopObservingMediaSinks=function(a){this.Cb.stopObservingMediaSinks(a)};d.startObservingMediaRoutes=function(a){this.Cb.startObservingMediaRoutes(a)};d.stopObservingMediaRoutes=function(a){this.Cb.stopObservingMediaRoutes(a)};d.pa=function(a){return this.Cb.pa(a)};d.Wv=function(a){return new zn(a)};d.MC=function(a){return this.sa.pa(a)};
d.M3=function(a,b,c,e){var f=this,h=Dn(a),k=this.MC(b);if(!k)return Promise.reject(Error("Attempting custom launch with closed route"));var n=h.appName;if(!n)return Promise.reject(Error("No app name given"));var q=kk(a);if(!q)return Promise.reject(Error("No client ID"));var z=null;return this.Wv(k).oC(n).then(function(a){if(!a.Eh)return Promise.reject(Error("Failed to get app info"));z=a.Eh}).then(function(){return f.Cb.Dg(b,a,!0,n,e,c)}).then(function(a){var b={routeId:a.id,sinkId:k.getId(),appName:n,
Eh:z,launchParameter:h.launchParameter,session:null,clientId:null};f.Cm.set(a.id,b);f.W2(b,q);return a})};d.o$=function(a){return mo.test(a)};d.createRoute=function(a,b,c,e,f,h,k){return this.o$(a)?Qg(this.M3(a,b,e,c)):this.Cb.createRoute(a,b,c,e,f,h,k)};
d.terminateRoute=function(a){var b=this.Cm.get(a);if(b&&b.session&&b.clientId){var c={receiver:this.FB(b.sinkId),action:chrome.cast.mq.STOP},c=new Rj("receiver_action",c);c.clientId=b.clientId;this.L.eg(this,b.routeId,c);this.L.onPresentationConnectionStateChanged(b.routeId,"terminated")}return this.Cb.terminateRoute(a)};
d.sendRouteMessage=function(a,b,c){var e=JSON.parse(b);switch(e.type){case "client_connect":return this.bga(a,e.clientId);case "custom_dial_launch":if(this.qs.contains(e.sequenceNumber))return this.Hba(a,e);break;case "v2_message":if("STOP"==e.message.type)return this.terminateRoute(a),Promise.resolve()}return this.Cb.sendRouteMessage(a,b,c)};d.sendRouteBinaryMessage=function(a){return Promise.reject(Error("Route "+a+" does not support sending binary data."))};
d.X6=function(){var a=String(this.pt);this.pt=(this.pt+1)%9007199254740992;return a};d.W2=function(a,b){var c=this.FB(a.sinkId),e=new Rj("receiver_action",{receiver:c,action:chrome.cast.mq.CAST});e.clientId=b;this.L.eg(this,a.routeId,e);c=new chrome.cast.M(this.X6(),"",a.appName,[],c);a.session=c;a.clientId=b;c=new Rj("new_session",c);c.clientId=b;this.L.eg(this,a.routeId,c)};
d.Hba=function(a,b){this.qs.remove(b.sequenceNumber);b=b.message;a=this.Cm.get(a);if(!a)return Promise.reject(Error("Unknown route"));if(b&&!b.doLaunch)return Promise.resolve();var c=this.MC(a.sinkId);if(!c)return Promise.reject(Error("Custom launch response for sink that no longer exists"));var c=new zn(c),e=a.launchParameter,e=(b?b.launchParameter:null)||e;return c.launchApp(a.appName,e)};
d.FB=function(a){var b=this.MC(a);a=new chrome.cast.qA(a,b.jo());a.ipAddress=b.Ga;a.receiverType=chrome.cast.nu.DIAL;return a};d.W6=function(){var a=this.Im;this.Im=(this.Im+1)%9007199254740992;return a};
d.bga=function(a,b){a=this.Cm.get(a);if(!a)return Promise.reject(Error("Unknown route"));var c=this.FB(a.sinkId);c.receiverType=chrome.cast.nu.DIAL;c=new Rj("custom_dial_launch",new chrome.cast.AJ(c,a.Eh.state,a.Eh.extraData));c.clientId=b;c.sequenceNumber=this.W6();this.qs.add(c.sequenceNumber);this.L.eg(this,a.routeId,c);return Promise.resolve()};d.qo=function(a){return this.Cb.qo(a)};d.po=function(a){return this.Cb.po(a)};d.zq=function(a,b){return this.Cb.zq(a,b)};
d.zn=function(a,b,c){return this.Cb.zn(a,b,c)};d.connectRouteByRouteId=function(a,b,c,e,f){return this.Cb.connectRouteByRouteId(a,b,c,e,f)};d.joinRoute=function(a,b,c,e,f,h){return this.Cb.joinRoute(a,b,c,e,f,h)};d.detachRoute=function(a){this.Cm.remove(a);this.Cb.detachRoute(a)};d.sf=function(){this.L.sf()};d.onSinkAvailabilityUpdated=function(a,b){this.L.onSinkAvailabilityUpdated(a,b)};d.fm=function(a,b){this.L.fm(this,b)};d.Vj=function(a,b){this.L.Vj(this,b)};
d.Wj=function(a,b){this.L.Wj(this,b)};d.eg=function(a,b,c){this.L.eg(this,b,c)};d.onPresentationConnectionStateChanged=function(a,b){this.L.onPresentationConnectionStateChanged(a,b)};d.onPresentationConnectionClosed=function(a,b,c){this.L.onPresentationConnectionClosed(a,b,c)};d.xD=function(a){return this.L.xD(a)};d.KD=function(){return this.L.KD()};d.ei=function(){return this.L.ei()};d.Bx=function(a,b,c){this.L.Bx(this,b,c)};d.HF=function(a){this.L.HF(a)};d.gm=function(a){this.Cb.gm(a)};d.fg=function(a){this.Cb.fg(a)};
d.Ee=function(a){this.Cb.Ee(a)};d.Jt=function(){};d.Lz=function(){};d.searchSinks=function(a,b){return this.Cb.searchSinks(a,b)};d.GG=function(a){this.L.GG(a)};d.AE=function(){return this.L.AE()};d.np=function(a,b){return this.L.np(a,b)};var lo=function(a,b,c,e){this.Fga=a;this.sequenceNumber=b;this.Dha=c;this.V$=e},mo=/__dialAppName__/;var no=function(a,b){this.Gb=a;this.Ila=b;this.Bi=new Ec;this.R=this.Bi.promise;this.ec=Lg.fw(a.id);this.Gd=new Ec;this.ie=!1;this.At();this.bI();this.Xb(new Lh("GET_TURN_CREDENTIALS"))};d=no.prototype;d.start=function(){var a=this;return this.R.then(function(b){if(b.Jj())return Promise.reject(Error("Presentation already started"));b.start();return a.Gd.promise})};d.stop=function(){var a=this;this.ie=!1;return this.R.then(function(b){b.stop();a.R=Promise.reject(Error("Peer connection has already been stopped"))})};
d.At=function(){var a=this;this.ec.onMessage=function(b){if(b.type)switch(b.type){case "TURN_CREDENTIALS":a.Bi.resolve(new Ph(a.Gb.id,b.data.credentials));break;case "ANSWER":a.R.then(function(a){a.setRemoteDescription(b.data)});break;case "STOP":a.Gd.reject("Stop signal received");a.stop();break;default:throw Error("Unknown message type: "+b.type);}else a.R.then(function(a){a.eha({type:"PRESENTATION_CONNECTION_MESSAGE",data:b})})}};
d.bI=function(){var a=this;this.R.then(function(b){b.IW(function(b){a.Xb(new Lh("OFFER",new Nh(b,null,null,a.Ila)))});b.HW(function(b){b=Mh(b);"STOP"==b.type&&a.stop();a.Xb(b)});b.GW(function(){a.ie=!0;a.Xb(new Lh("SESSION_START_SUCCESS"));a.Gd.resolve(a.Gb)});b.EW(function(){a.Xb(new Lh("SESSION_END"))});b.FW(function(b){a.ie||a.Gd.reject(b);a.Xb(new Lh("SESSION_FAILURE"))})})};d.Xb=function(a){this.ec.sendMessage(a,oo)};var oo={channelType:"cloud"};var po=function(a){this.L=a;this.Ab=new Map;this.ly=new Map;this.Dt=[];this.qg=this.Uo=this.td=this.Zh=this.wo=null;this.Yo=this.Ok=this.lj=!1;this.Et=new Map;this.Sp=new Map;Wh(this)};d=po.prototype;d.getName=function(){return"cloud"};
d.Tb=function(){var a=this;this.a.info("Initializing Cloud MRP");var b=jn.ga(),c=b.I5(this);this.Dt.push(c);this.wo=b.v6(this);this.Dt.push(this.wo);this.Zh=b.lO();this.td=b.ci();this.Uo=b.P6(this);this.qg=b.T7();this.qg.F5().then(function(b){a.lj=b;a.a.info("Cloud enabled setting: "+a.lj)});this.qg.H5().then(function(b){a.Ok=b;a.a.info("Cloud on setting: "+a.Ok)});this.qg.Oja(function(b){a.lj=b;a.a.info("Cloud enabled setting: "+a.lj);a.lj&&a.qR()});this.qg.Z6().then(function(b){a.Yo=b;a.a.info("Privacy notified setting: "+
a.Yo)})};d.li=function(){return Array.from(this.Ab.values())};
d.hr=function(a){if(!this.yE(a))return Mk;this.a.C("GetAvailableSinks for "+a);var b=[];if(this.Ok||this.vla())b=this.qR();this.Sp.clear();for(var c={},e=ia(this.Et.values()),f=e.next();!f.done;c={qp:c.qp,Pv:c.Pv},f=e.next())c.qp=f.value,c.Pv=!1,b.forEach(function(a){return function(b){b.yb.id==a.qp.yb.id&&(a.Pv=!0,b.yb.friendlyName=a.qp.yb.friendlyName)}}(c)),c.Pv||this.Sp.set(c.qp.yb.id,c.qp);b=b.concat.apply(b,[].concat(ka(this.Sp.values())));this.a.C(function(){return"Available sinks are..."+
JSON.stringify(b)});c=b.map(function(a){return a.yb});this.wo&&(c=c.concat(qo));return new Lk(c,-1!=a.indexOf("0F5096E8")?sh:null)};d.qR=function(){var a=[];this.a.info("Checking cloud discovery services");Pi.ga().Uw=u();this.Dt.forEach(function(b){b=b.gf();a=a.concat(b)});return a};d.startObservingMediaSinks=function(){};d.stopObservingMediaSinks=function(){};d.startObservingMediaRoutes=function(){};d.stopObservingMediaRoutes=function(){};d.pa=function(a){return(a=this.kr(a))?a.yb:null};
d.createRoute=function(a,b,c,e,f,h,k){var n=this;this.a.info("createRoute called");this.a.C("urn: "+a+" sinkId:"+b);if(f=this.ly.get(b))return this.L.Lz(this,f,a,c,k,function(b){b.mediaSource=a;b.lf.tabId=k;return Og(b)}).mB(function(a){n.L.Wj(n,a);return a});f=this.kr(b);return this.uv(a,f,b,c,e,h,k)};
d.NL=function(a,b,c,e){a instanceof Kk&&2==a.errorCode?this.Zm(b,6,null):(this.a.error("Error on start session",a instanceof Error?a:Error("Expected an Error value, got "+a)),this.Zm(b,e,new Mg(Sm,"warning","dismiss")));this.wo&&this.wo.Ofa(c)&&this.fg([c.yb])};
d.uv=function(a,b,c,e,f,h,k){var n=this;if(f)return Pg(Error("not supported"));f=!1;switch(this.wD(b)){case "cloud":hm(1);break;case "mesi":f=!0,this.Yo||(this.Yo=!0,this.qg.Nja(),h=new Mg(Vm,"notification","learn_more"),h.Eka(["dismiss"]),h.Yia(6320939),this.L.ei().send(h)),hm(0)}Pi.ga().tm=new Oi(b.model,null);var q=ni(e,this.getName(),c,a,!0,"",null);f&&(q.customControllerPath="cloud_route_details/view.html?routeId="+q.id);this.Ab.set(q.id,q);this.ly.set(c,q);this.Et.set(q.id,b);this.L.fm(this,
q);this.L.np(this.Ca(),!0);if(rh(a)&&!f)return this.a.info("starting presentation on route: "+q.id),this.Rla(q,a).catch(function(a){n.NL(a,q,b,7);throw a;});this.a.info("starting mirroring on route: "+q.id);q.lf={tabId:k,sessionId:"",lI:"",sX:b.model};rh(a)&&(q.isOffscreenPresentation=!0);return this.L.Jt(this,q,e).catch(function(a){n.NL(a,q,b,5);throw a;})};
d.terminateRoute=function(a){var b=this.Ab.get(a);return b?this.Zm(b,0,null):Promise.reject(new Kk(3,"Route in cloud provider not found for routeId "+a))};
d.Zm=function(a,b,c){this.a.info("terminating route: "+a.id);this.Ab.delete(a.id);this.ly.delete(a.sinkId);var e=this.Et.get(a.id);this.Et.delete(a.id);c&&this.ei().send(c);gh("MediaRouter.Cloud.Session.End",b,cm);switch(b){case 1:break;default:this.r2(e)}this.L.Vj(this,a);0==this.Ab.size&&this.L.np(this.Ca(),!1);this.L.onPresentationConnectionStateChanged(a.id,"terminated");this.Sp.has(a.sinkId)&&(b=this.Sp.get(a.sinkId),this.fg([b.yb]),this.Sp.delete(a.sinkId));return Promise.resolve()};
d.sendRouteMessage=function(a,b,c){if(c&&c.channelType){c=c.channelType;var e=(a=this.Ab.get(a)||void 0)?this.kr(a.sinkId):void 0;return this.Uo.Aea(c,b,a,e)}return p(b)?(this.Je(b,a),Promise.resolve()):Promise.reject(Error("Channel type missing"))};d.sendRouteBinaryMessage=function(a){return Promise.reject(Error("Route "+a+" does not support sending binary data."))};
d.qo=function(a){var b=new Kh;"hangouts"!=this.po(a)&&(b.senderSideLetterboxing=!0);b.uS();this.a.info("Settings for "+a+": "+b.Ez());return b.shouldCaptureAudio||b.shouldCaptureVideo?b:null};d.po=function(a){var b=null;a=this.kr(a);switch(this.wD(a)){case "cloud":b="webrtc";break;case "mesi":b=a.dh?"meetings":"hangouts"}return b};d.zq=function(a,b){this.a.C("Checking canRoute: "+a+" for sinkId: "+b);return this.yE(a)&&!!this.pa(b)};
d.zn=function(a,b){return"https://hangouts.google.com/cloudmrp-mirroring"==a&&this.Ab.has(b)};d.joinRoute=function(a,b){return(a=this.Ab.get(b))?Og(a):Pg(Error("not supported"))};d.connectRouteByRouteId=function(){return Pg(Error("not supported"))};d.detachRoute=function(){};d.NF=function(a){this.a.info(a.length+" sinks added");0<a.length&&!this.Ok&&(this.qg.Lma(),this.Ok=!0);a=this.kr(a[0].id);Pi.ga().sm=new Oi(a.model,null);this.L.sf();this.L.onSinkAvailabilityUpdated(this,2);this.a.info("sinkAvailability changed to AVAILABLE")};
d.fg=function(a){this.a.info(a.length+" sinks removed");this.Dt.some(function(a){return 0<a.gf().length})||(this.L.onSinkAvailabilityUpdated(this,0),this.a.info("sinkAvailability changed to UNAVAILABLE"));this.L.sf()};d.sf=function(a){this.a.info(a.length+" sinks updated");this.L.sf()};d.ei=function(){return this.L.ei()};d.Je=function(a,b,c){c?this.L.eg(this,b,a):this.L.Bx(this,b,a)};d.kr=function(a){var b=this.e6(a);b||(b=this.L7(a));return b};
d.e6=function(a){var b=null;this.Dt.some(function(c){b=c.pa(a);return!!b});return b};d.L7=function(a){var b=null;(a=this.ly.get(a))&&(b=this.Et.get(a.id));return b};d.r2=function(a){switch(this.wD(a)){case "cloud":this.Zh.sha(a.deviceId)}};d.wD=function(a){return a.HX("cloud")?"cloud":a.HX("mesi")?"mesi":null};d.vla=function(){var a=Pi.ga().Uw;return 3E5<=Date.now()-a};
d.yE=function(a){var b=qh(a);a=rh(a);if(this.td.Ko&&!this.td.uh&&b)return this.L.onSinkAvailabilityUpdated(this,2),!0;var c=!1;this.lj&&this.td.uh&&(c=!0);return chrome.declarativeWebRequest||this.td.J$()||!a?c&&(b||a):!1};d.searchSinks=function(a,b){if(!this.yE(a))return null;(a=this.wo.g0(b))&&this.NF([a]);return a};d.Ca=function(){return"CloudProvider"};d.getData=function(){return[void 0,{cloudEnabled:this.lj,cloudOn:this.Ok,notifiedHangoutsPrivacy:this.Yo}]};
d.tb=function(){var a=Uh(this);a&&(a.cloudEnabled&&(this.lj=a.cloudEnabled),a.cloudOn&&(this.Ok=a.cloudOn),a.notifiedHangoutsPrivacy&&(this.Yo=a.notifiedHangoutsPrivacy))};d.Rla=function(a,b){a=new no(a,b);return Qg(a.start())};d.a=D("mr.CloudProvider");var qo=new zi("pseudo:cloud","","hangout","Add a hangout","default");var ro=function(){ej.call(this,12,"ExternalMessageListener","mr.ProviderManager",chrome.runtime.onMessageExternal)};ja(ro,ej);ro.prototype.Sz=function(a,b){return b.id&&-1!=so.indexOf(b.id)?"start"==a.type||"stop"==a.type:!1};ro.prototype.LB=function(){return!0};var uo=function(){to||(to=new ro);return to},to=null,so=["idmofbkcelhplfjnmmdolenpigiiiecc","ggedfkijiiammpnbdadhllnehapomdge","njjegkblellcjnakomndbaloifhcoccg"];var vo=function(){ej.call(this,11,"InternalMessageListener","mr.ProviderManager",chrome.runtime.onMessage)};ja(vo,ej);vo.prototype.Sz=function(a,b){return"retrieve_log_data"==a.type&&b.id==chrome.runtime.id&&b.url=="chrome-extension://"+b.id+"/feedback.html"};vo.prototype.LB=function(){return!0};var xo=function(){wo||(wo=new vo);return wo},wo=null;var yo,zo,Ao=D("mr.Init"),Bo=function(a){var b=new Xk(a),c=new ko(a,b),b=[b,c];b.push(new po(a));return b};jl.ga().init();yo=new ah("MediaRouter.Provider.WakeDuration");zo=new ql;
var Co=(new Promise(function(a,b){switch(window.location.host){case "enhhojjnijigcajfphajepfemndkmdlo":a();break;case "pkedcjkdefgpdelpbcmbmeomcjbeemfm":chrome.management.get("enhhojjnijigcajfphajepfemndkmdlo",function(c){chrome.runtime.lastError||!c.enabled?a():b(Error("Dev extension is enabled"))});break;default:b(Error("Unknown extension id"))}})).then(function(){return chrome.mojoPrivate&&chrome.mojoPrivate.requireAsync?new Promise(function(a){chrome.mojoPrivate.requireAsync("media_router_bindings").then(function(b){b.start().then(function(c){a({mrService:b,mrInstanceId:c})})})}):
Promise.reject(Error("No mojo service loaded"))}).then(function(a){if(!a.mrService)throw Error("Failed to get MR service");var b=a.mrInstanceId;if(!b)throw Error("Failed to get MR instance ID.");Ao.info("MR instance ID: "+b);a=a.mrService;if(!zo)throw Error("providerManager not initialized.");a.setHandlers(zo);Yh(b)&&yo.Ap("MediaRouter.Provider.FirstWakeDuration");chrome.runtime.onSuspend.addListener(yo.end.bind(yo));bi(b);jl.ga().vfa();b=Bo(zo);window.addEventListener("unhandledrejection",function(a){a=
a.reason;a.stack||(a=Error(a));Ao.error("Unhandled promise rejection.",a)});zo.Tb(a,b)}).then(void 0,function(a){Ao.u(a.message);throw a;});[].concat([uo(),xo()],ka(ao()),ka([hj(),jj()]),ka([mm()])).forEach(function(a){return a.n0()});uo().addListener();xo().addListener();Co.then(void 0,function(){return window.close()});
