'use strict';var Do={TAB:0,zJ:1,VZ:2},Eo=function(a){gh("MediaRouter.CastStreaming.Start.Success",a,Do)};var Fo=D("mr.mirror.cast.LogUploader"),Ho=function(a,b,c){Go("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},Go=function(a,b,c,e){if(0==b.size)Fo.info("Trying to upload an empty file to Crash"),e&&e(null);else{var f=new FormData;f.append("prod","Cast");f.append("ver",chrome.runtime.getManifest().version);f.append(a,b);c&&f.append("comments",c);Pf("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;a.Od()?(b=a.ff(),Fo.info("Upload to Crash succeeded: "+
b)):Fo.info("Upload to Crash failed. HTTP status: "+a.Sa());e&&e(b)},"POST",f,void 0,3E4)}};var Io=function(){this.js=0;Wh(this)},Ko=function(){Jo||(Jo=new Io);return Jo};Io.prototype.jja=function(a){this.js=a};Io.prototype.tla=function(){var a={fraction:.01,autoSubmitTimeLimitMillis:6048E5},b=a.autoSubmitTimeLimitMillis,c=Date.now();return this.js&&b&&c-this.js<b?!1:Math.random()<a.fraction};
var Mo=function(a,b,c,e){var f=new Lo;f.extVersion=chrome.runtime.getManifest().version;f.extChannel="public";f.minBitrate=c.minVideoBitrate;f.maxBitrate=c.maxVideoBitrate;f.resolution=c.maxWidth+"x"+c.maxHeight;f.minResolution=c.minWidth+"x"+c.minHeight;if(f.minResolution==f.resolution)f.resolutionChangePolicy="fixed";else if(c.senderSideLetterboxing){var h=c.mP();f.minResolution+=" (altered to: "+h.width+"x"+h.height+")";f.resolutionChangePolicy="fixed-aspect-ratio"}else f.resolutionChangePolicy=
"variable";f.maxFrameRate=c.maxFrameRate;f.minLatency=c.minLatencyMillis;f.maxLatency=c.maxLatencyMillis;f.animatedLatency=c.animatedLatencyMillis;f.useDscp=c.dscpEnabled;f.useTdls=c.useTdls;null!=b&&(f.receiverVersion=b);null!=a&&(f.receiverProductName=a);e.length&&(f.receiverStatusData=e);return f},Oo=function(a,b,c,e,f){No.info("getRawEvents");return new Promise(function(h,k){var n=function(b){No.info("Got receiver version: "+b);b=JSON.stringify(Mo(c,b,e,f));chrome.cast.streaming.rtpStream.getRawEvents(a,
b,h)};"Chromecast"==c?Yf(b).then(n,k):n(null)})},Po=function(a,b,c,e){No.info("getStats");return new Promise(function(f,h){var k=function(b){No.info("Got receiver version: "+b);var h=Mo(c,b,e,[]);chrome.cast.streaming.rtpStream.getStats(a,function(a){var b={tags:h};Pb(b,a);f(b)})};"Chromecast"==c?Yf(b).then(k,h):k(null)})};Io.prototype.Ca=function(){return"mirror.cast.LogUtils"};Io.prototype.getData=function(){return[void 0,{lastAutoSubmitMillis:this.js}]};
Io.prototype.tb=function(){var a=Uh(this);this.js=a&&a.lastAutoSubmitMillis||0};var Jo=null,No=D("mr.mirror.cast.LogUtils"),Lo=function(){this.ext="MR";this.senderProductName="Google Chrome";this.senderVersion=zk;this.senderPlatform=ec;this.senderUserAgent=Qb||""};var Qo=D("mr.NetworkUtils"),Ro=function(a,b){return Vg?new Promise(function(c,e){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(Qo.u("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),e("Unable to set TDLS state to "+b+".")):(Qo.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var So=function(a){this.V9=a;this.Px=Promise.resolve(a)};So.prototype.Ef=function(a,b){return this.AB(function(b){return b==a},b)};So.prototype.B2=function(a,b){return this.AB(function(b){return-1!=a.indexOf(b)},b)};So.prototype.ay=function(a){var b=this;this.Px=this.Px.catch(function(){return b.V9});return this.AB(function(){return!0},a)};
So.prototype.AB=function(a,b){var c,e,f=new Promise(function(a,b){c=a;e=b});this.Px=this.Px.then(function(f){if(!a(f))return e(Error("Operation requires a different starting checkpoint than "+f)),Promise.resolve(f);var h=new To(f),n;try{n=b(h)}catch(q){n=Promise.reject(q)}return n.then(function(a){return c(a)},function(a){return e(a)}).then(function(){if(null===h.hC)throw Error("A prior operation that started at "+(f+" did not complete."));return h.hC})},function(a){e(a);throw a;});return f};
var To=function(a){this.ema=a;this.hC=null};To.prototype.complete=function(a){this.hC="number"===typeof a?a:this.ema};var Uo={yra:"OFFER",yoa:"ANSWER",Tra:"PRESENTATION",Upa:"GET_STATUS",Isa:"STATUS_RESPONSE",Tpa:"GET_CAPABILITIES",Voa:"CAPABILITIES_RESPONSE",rsa:"RPC"};var Vo=function(){this.capabilities=this.status=this.yu=this.error=this.rpc=this.result=this.type=this.nH=this.sessionId=null},Yo=function(a){var b;try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var c;Wo(JSON.parse(a),function(a){c=Xo(a)},function(){throw Error("non-Object result from JSON parse");});return c}catch(e){b=e instanceof SyntaxError?"JSON parse error: "+e.message:"Type coercion error: "+e.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(b+". Input was "+a);},Xo=function(a){var b=new Vo;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Zo(a.seqNum,function(a){b.nH=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),e=ia(Object.keys(Uo)),f=e.next();!f.done;f=e.next())if(Uo[f.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(ka(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}Wo(a.error,function(a){b.error=$o(a)},function(){throw Error('"error" must be an Object');});Wo(a.answer,function(a){b.yu=ap(a)},function(){throw Error('"answer" must be an Object');});Wo(a.status,function(a){b.status=bp(a)},function(){throw Error('"status" must be an Object');
});Wo(a.capabilities,function(a){b.capabilities=cp(a)},function(){throw Error('"capabilities" must be an Object');});return b},Wo=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Zo=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},dp=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},ep=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},fp=function(){this.fY=null;this.py=[];this.nI=
[];this.UK=this.wU=this.EZ=null},ap=function(a){var b=new fp;Zo(a.udpPort,function(a){b.fY=a},function(){throw Error('"answer.udpPort" must be a number');});dp(a.sendIndexes,function(a){b.py=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});dp(a.ssrcs,function(a){b.nI=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.EZ=String(a.IV));"receiverGetStatus"in a&&(b.wU="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&
(b.UK=String(a.castMode));return b},gp=function(){this.details=this.description=this.code=null},$o=function(a){var b=new gp;Zo(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Wo(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},hp=function(){this.WI=this.VI=null},bp=function(a){var b=new hp;Zo(a.wifiSnr,function(a){b.VI=a},function(){throw Error('"status.wifiSnr" must be a number');
});dp(a.wifiSpeed,function(a){b.WI=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},ip=function(){this.O$=this.IS=null},cp=function(a){var b=new ip;ep(a.mediaCaps,function(a){b.IS=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.O$=a.map(function(a){var b;Wo(a,function(a){b=jp(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},kp=function(){this.I3=this.iea=this.hea=this.gea=this.yna=this.M0=this.Wga=this.u2=this.initDataTypes=this.N$=null},jp=function(a){var b=new kp;"keySystemName"in a&&(b.N$=String(a.keySystemName));ep(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});ep(a.codecs,function(a){b.u2=a},function(){throw Error('"capabilities.codecs" must be an array');});ep(a.secureCodecs,function(a){b.Wga=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});ep(a.audioRobustness,function(a){b.M0=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});ep(a.videoRobustness,function(a){b.yna=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.gea=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.hea=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.iea=String(a.persistentStateSupport));
"distinctiveIdentifierSupport"in a&&(b.I3=String(a.distinctiveIdentifierSupport));return b};var lp=function(a){this.a=D("mr.mirror.cast.MessageDispatcher");this.ky=a;this.ec=null;this.Pt=new Map;this.wF=0};d=lp.prototype;d.subscribe=function(a,b){if(this.Pt.has(a))throw Error("Attempt to multiple-subscribe to the same response type: "+a);this.Pt.set(a,b);this.wF=0;this.a.C("Added subscriber for "+a+"-type messages.");this.ec||(this.ec=Lg.fw(this.ky),this.ec.onMessage=this.Dx.bind(this))};
d.unsubscribe=function(a){this.Pt.delete(a)&&this.a.C(function(){return"Removed subscriber of "+a+"-type messages."});0==this.Pt.size&&this.ec&&(this.ec.fb(),this.ec=null)};d.sendMessage=function(a){return this.ec?"RPC"==a.type?this.ec.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.ec.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
d.SU=function(a,b,c,e){var f=this,h=null,k=function(){f.unsubscribe(b);null!=h&&(clearTimeout(h),h=null)};try{this.subscribe(b,function(a){e(a)&&k()})}catch(n){e(null,n);return}h=setTimeout(function(){k();e(null,Error("timeout"))},c);this.sendMessage(a).catch(function(a){k();e(null,a)})};
d.Dx=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){var b;do{b=void 0;try{b=Yo(a.data)}catch(e){b=e.message;break}if(b.type){var c=this.Pt.get(b.type);if(c)try{c(b);return}catch(e){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+e.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>this.wF?
this.a.u(b):this.a.C(b);++this.wF}};var mp=chrome.cast.streaming,op=function(a,b,c,e,f){this.H=a.sessionId;this.jg=a.lI;this.Vs=a.sX;this.Mb=b;this.Li=c;this.Rd=e;this.Mga=np(f,"onAnswer",this.jg);this.Nga=np(f,"onSessionStop",this.jg);this.a=D("mr.mirror.cast.StreamingLaunchWorkflow");this.Kc=new So(1);this.jt=this.xU=this.Zt=this.Id=this.Wc=this.Rb=this.Jb=null};d=op.prototype;
d.start=function(a,b,c){var e=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var f=a instanceof pp,h=b instanceof pp;(f&&b&&!h||h&&a&&!f)&&w("Mixing remoting and non-remoting tracks");return this.Kc.Ef(1,function(f){e.Jb=a;e.Rb=b;e.a.info(function(){return"Launching streaming for "+e.Rv()+" "+("to a "+e.Vs+".")});return e.O2().then(e.X2.bind(e)).then(function(a){return e.oha(a).then(function(b){e.Mga();var f=e.Xga(b,a);e.Wc=e.aM(e.Wc,f);e.Id=e.aM(e.Id,f);if(!e.Wc&&!e.Id)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));e.xU=!!b.wU;e.jt=function(a,b){a==e.Wc?c("Audio stream (id="+a+") error: "+b):a==e.Id&&c("Video stream (id="+a+") error: "+b)};mp.rtpStream.onError.addListener(e.jt);return e.bma(b,f)})}).then(function(){e.a.info(function(){return"Launched streaming for "+e.Rv()});f.complete(2);return{zK:null!=e.Wc?e.Wc.toString(16):null,LY:null!=e.Id?e.Id.toString(16):null}})})};
d.stop=function(){var a=this;return this.Kc.ay(function(b){if(a.Jb||a.Rb)a.a.info(function(){return"Stopping streaming for "+a.Rv()+"."}),a.jt&&(mp.rtpStream.onError.removeListener(a.jt),a.jt=null),a.Wc&&(mp.rtpStream.stop(a.Wc),mp.rtpStream.destroy(a.Wc),a.Wc=null),a.Id&&(mp.rtpStream.stop(a.Id),mp.rtpStream.destroy(a.Id),a.Id=null),a.Zt&&(mp.udpTransport.destroy(a.Zt),a.Zt=null),a.Nga(),a.a.info(function(){return"Stopped streaming for "+a.Rv()+"."}),a.Jb=null,a.Rb=null;b.complete(1);return Promise.resolve()})};
d.BG=function(){return!!this.xU};d.zj=function(a){var b=this;return Promise.all([this.Wc&&Oo(this.Wc,this.jg,this.Vs,this.Mb,a),this.Id&&Oo(this.Id,this.jg,this.Vs,this.Mb,a)]).then(function(a){a=new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"});if(0==a.size)throw Error("No logs available to retrieve.");b.a.info("Events blob size: "+a.size);return a})};
d.getStats=function(a){return Promise.all([this.Wc&&Po(this.Wc,this.jg,this.Vs,this.Mb),this.Id&&Po(this.Id,this.jg,this.Vs,this.Mb),0<a.length?{receiverStatusData:a}:void 0]).then(function(a){a=Object.assign.apply(Object,[].concat([{}],ka(a.filter(function(a){return!!a}))));if(0==Object.getOwnPropertyNames(a).length)throw Error("No stats available to retrieve.");return a})};
d.Rv=function(){var a;a=this.Jb&&this.Rb?"audio+video ":this.Jb?"audio-only ":this.Rb?"video-only ":"";return this.Jb instanceof pp||this.Rb instanceof pp?a+"remoting":a+"streaming"};
d.O2=function(){var a=this;return new Promise(function(b){var c=function(c,f,h){c&&!a.Jb&&(mp.rtpStream.destroy(c),c=null);f&&!a.Rb&&(mp.rtpStream.destroy(f),f=null);a.a.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+f+"."});a.Wc=c;a.Id=f;a.Zt=h;b()};a.Jb instanceof pp||a.Rb instanceof pp?mp.session.create(null,null,c):mp.session.create(a.Jb,a.Rb,c)})};
d.X2=function(){for(var a=Ai(window.crypto.getRandomValues(new Uint8Array(16))),b=Ai(window.crypto.getRandomValues(new Uint8Array(16))),c=[],e=ia([this.Wc,this.Id]),f=e.next();!f.done;f=e.next())if(f=f.value)for(var h=f==this.Wc,k=h?127:96,n=h?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,q=h?48E3:9E4,z=ia(mp.rtpStream.getSupportedParams(f)),B=z.next();!B.done;B=z.next())B=B.value,B.payload.payloadType=k,B.payload.maxLatency=this.Mb.maxLatencyMillis,B.payload.minLatency=
this.Mb.minLatencyMillis,B.payload.animatedLatency=this.Mb.animatedLatencyMillis,B.payload.ssrc=n,B.payload.clockRate=q,B.payload.aesKey=a,B.payload.aesIvMask=b,h?(B.payload.channels=2,B.payload.maxBitrate=this.Mb.audioBitrate,B.payload.maxFrameRate=100):(B.payload.minBitrate=this.Mb.minVideoBitrate,B.payload.maxBitrate=this.Mb.maxVideoBitrate,B.payload.maxFrameRate=this.Mb.maxFrameRate),c.push(new qp(f,B));return c};
d.aM=function(a,b){a&&!b.some(function(b){return b.Ri==a})&&(this.a.u("Destroying RTP stream not selected by the receiver: id="+a),mp.rtpStream.destroy(a),a=null);return a};
d.oha=function(a){var b=this;return new Promise(function(c,e){for(var f=[],h=0;h<a.length;++h){var k=a[h].params,n={index:h,codecName:k.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:k.payload.payloadType,ssrc:k.payload.ssrc,targetDelay:k.payload.animatedLatency,aesKey:k.payload.aesKey,aesIvMask:k.payload.aesIvMask,timeBase:"1/"+k.payload.clockRate,receiverRtcpEventLog:b.Mb.enableLogging,rtpExtensions:["adaptive_playout_delay"]};b.Mb.dscpEnabled&&(n.receiverRtcpDscp=46);127==k.payload.payloadType?
Object.assign(n,{type:"audio_source",bitRate:0<k.payload.maxBitrate?1E3*k.payload.maxBitrate:60*k.payload.maxFrameRate+k.payload.clockRate*k.payload.channels,sampleRate:k.payload.clockRate,channels:k.payload.channels}):Object.assign(n,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*k.payload.maxFrameRate)+"/1000",maxBitRate:1E3*k.payload.maxBitrate,resolutions:[{width:b.Mb.maxWidth,height:b.Mb.maxHeight}]});f.push(n)}var q=b.Jb instanceof pp||b.Rb instanceof pp?"remoting":"mirroring",
z={type:"OFFER",sessionId:b.H,seqNum:b.Li.Er(),offer:{castMode:q,receiverGetStatus:!0,supportedStreams:f}};b.a.info(function(){return"Sending OFFER message: "+JSON.stringify(z)});b.Rd.SU(z,"ANSWER",1E4,function(a,f){if(null==a)e(f);else if("ok"==a.result&&a.yu){if(a.nH!=z.seqNum)return b.a.u("Ignoring ANSWER for OFFER with different seqNum: "+JSON.stringify(a)),!1;((f=a.yu.UK)&&f!=q||!f&&"mirroring"!=q)&&b.a.error("Expected receiver to ANSWER with castMode="+q+", but got: "+f);b.a.C(function(){return"Received ANSWER: "+
JSON.stringify(a)});c(a.yu)}else e(Error("Non-OK ANSWER received: "+JSON.stringify(a)));return!0})})};
d.Xga=function(a,b){if(a.py.length!=a.nI.length)return this.a.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(a)),[];for(var c=[],e={},f=0;f<a.py.length;e={candidate:e.candidate},++f){var h=a.py[f];if(0>h||h>=b.length)return this.a.error("Receiver selected invalid index ("+h+" < "+b.length+") in ANSWER: "+JSON.stringify(a)),[];e.candidate=b[h];if(c.some(function(a){return function(b){return b.Ri==a.candidate.Ri}}(e)))return this.a.error("Receiver selected same RTP stream twice in ANSWER: "+
JSON.stringify(a)),[];e.candidate.params.payload.feedbackSsrc=a.nI[h];if(c.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return this.a.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(a)),[];c.push(e.candidate)}return c};
d.bma=function(a,b){var c=this,e=null,f=function(){e&&(mp.rtpStream.onStarted.removeListener(e),e=null)};return(new Promise(function(f,k){var h=a.fY||2344;c.a.info(function(){return"Starting RTP streams to receiver at "+(c.jg+":"+h)+(" for selected offers: "+JSON.stringify(b))});var q=c.Zt||-1;c.Mb.dscpEnabled&&(c.a.info("Enabled DSCP in sender."),mp.udpTransport.setOptions(q,{DSCP:!0}));mp.udpTransport.setDestination(q,{address:c.jg,port:h});var z=new Set(b.map(function(a){return a.Ri}));e=function(a){z.delete(a);
0==z.size&&f()};mp.rtpStream.onStarted.addListener(e);for(var q=ia(b),B=q.next();!B.done;B=q.next())B=B.value,mp.rtpStream.toggleLogging(B.Ri,c.Mb.enableLogging),mp.rtpStream.start(B.Ri,B.params);setTimeout(function(){k(Error("Timeout: RTP streams failed to start."))},1E4)})).then(f).catch(function(a){f();throw a;})};
var np=function(a,b,c){var e=this;return a&&b in a?function(){try{a[b](c)}catch(f){e.a.error("Error from testHooks."+b,f)}}:function(){}},qp=function(a,b){this.Ri=a;this.params=b},pp=function(){};var sp=function(a,b,c,e,f,h){var k=Math.floor(16777216*Math.random()).toString(16),k="000000".substring(k.length)+k,n=a.mediaSource.replace("urn:x-org.chromium.media:source:tab:","urn:x-org.chromium.media:source:tab_content_remoting:"),k=ni("undefined","cast",k,n,!0,a.description,a.iconUrl);k.forDisplay=!1;k.offTheRecord=a.offTheRecord;k.lf=a.lf;this.gV=k;this.Zd=b;this.fh=new op(this.gV.lf,c,e,f,h);this.Rd=f;this.Kc=new So(1);this.Dm=new rp;this.a=D("mr.mirror.cast.MediaRemoter");this.nj=this.UB=
this.Zs=this.TG=null};d=sp.prototype;d.start=function(a){var b=this;return this.Kc.Ef(1,function(c){b.TG=a;b.Zs=tp().Cfa(b);c.complete(2);return Promise.resolve()})};d.stop=function(){var a=this;return this.Kc.ay(function(b){return a.gz().then(function(){tp().Qma(a);a.Zs=null;a.TG=null;b.complete(1)})})};d.ki=function(){return this.gV};
d.yea=function(a){var b=this;this.a.C(function(){return"Processing control message: "+a});var c=a.split(":"),e=(c.find(function(a){return a.startsWith("session=")})||"").substring(8);if(0==e.length)return this.a.error("Missing valid 'session' field in control message: "+a),Promise.resolve();switch(c[0]){case "START_CAST_REMOTING":return this.Wla(e).catch(function(a){b.a.error("Failed to start remoting",a);b.oy(e)});case "START_CAST_REMOTING_STREAMS":var f=c.some(function(a){return"audio=Y"==a}),c=
c.some(function(a){return"video=Y"==a});return this.Vla(e,f,c).then(this.hH.bind(this)).catch(function(a){b.a.error("Failed to start remoting streams",a);b.oy(e)});case "STOP_CAST_REMOTING":return this.hma(e).catch(function(a){b.a.error("Failed to stop remoting",a);b.oy(e)}).then(function(){b.hH("STOPPED_CAST_REMOTING:session="+e)});default:this.a.error("Unknown control message: "+a)}return Promise.resolve()};d.kha=function(a){return this.Dm.Hm(a)};
d.Wla=function(a){var b=this;if(null!=this.nj)return Promise.reject(Error("Attempt to start a second session ("+a+") during existing session ("+this.nj+")."));this.nj=a;var c=!1;this.a.info(function(){c=!0;return"Starting next media remoting session (id="+a+")."});c&&this.Dm.Xla(function(a){return b.a.info(a)});this.Dm.Tla();return this.Kc.Ef(2,function(a){return(0,b.TG)().then(function(c){b.UB=c;b.Rd.subscribe("RPC",function(a){a.rpc&&b.Dm.uha(a.rpc)});a.complete(3)}).catch(function(c){return b.gz().then(function(){a.complete();
throw c;})})})};
d.Vla=function(a,b,c){var e=this;return this.nj!=a?Promise.reject(Error("Cannot start streams for an unknown session ("+a+") during existing session ("+this.nj+")")):this.Kc.Ef(3,function(f){return e.fh.start(b?new pp:null,c?new pp:null,function(b){e.a.error("Error during streaming: "+b);e.oy(a)}).then(function(b){var c="STARTED_CAST_REMOTING_STREAMS:session="+a;b.zK&&(c+=":audio_stream_id="+b.zK);b.LY&&(c+=":video_stream_id="+b.LY);e.Dm.dma(function(a){return e.Rd.sendMessage(a)},function(a){return e.Zs.lha(a)});
f.complete(4);return c}).catch(function(a){return e.gz().then(function(){f.complete();throw a;})})})};d.hma=function(a){var b=this;if(this.nj!=a)return Promise.reject(Error("Attempting to stop an unknown session ("+a+") during existing session ("+this.nj+")."));this.nj=null;return this.Kc.B2([3,4],function(a){return b.gz().then(function(){return(0,b.UB)()}).then(function(){b.UB=null;a.complete(2)})})};
d.gz=function(){var a=this;return this.fh.stop().then(function(){a.Rd.unsubscribe("RPC");a.Dm.gma();a.Dm.CX()})};d.hH=function(a){this.Zs?(this.a.C(function(){return"Sending control message to browser: "+a}),this.Zs.dha(a)):this.a.C(function(){return"Dropping control message to browser: "+a})};d.oy=function(a){this.hH("FAILED_CAST_REMOTING:session="+a)};
var tp=function(){return(wh.get("mr.ProviderManager")||null).Hr("cast")},rp=function(){this.sy=this.ry=this.ig=null;this.SM=this.Mu=this.DB=this.Nu=this.EB=0;this.fy=null};d=rp.prototype;d.Tla=function(){this.ig=[];this.bH(performance.now())};d.dma=function(a,b){var c=this;this.ry=a;this.sy=b;this.ig?(a=this.ig,this.ig=null,a.forEach(function(a){return c.Hm(a.data).then(a.pha,a.vV)})):this.bH(performance.now())};
d.gma=function(){if(this.ig){var a=Error("Stop before delivering pending message");this.ig.forEach(function(b){return b.vV(a)});this.ig=null}this.sy=this.ry=null};d.Hm=function(a){var b=this;if(this.ry){var c=btoa(String.fromCharCode.apply(null,a));++this.EB;this.Nu+=a.length;return this.ry({type:"RPC",rpc:c})}return this.ig?new Promise(function(c,f){b.ig.push({data:a,pha:c,vV:f})}):Promise.reject(Error("RPC pipe not started"))};d.uha=function(a){this.sy&&(++this.DB,this.Mu+=a.length,this.sy(a))};
d.Xla=function(a){var b=this;this.CX();this.fy=setInterval(function(){a(b.saa())},3E3)};d.CX=function(){null!=this.fy&&(clearInterval(this.fy),this.fy=null)};d.bH=function(a){this.Mu=this.DB=this.Nu=this.EB=0;this.SM=a};
d.saa=function(){if(this.ig)return this.ig.length+" messages are waiting to send.";var a=performance.now(),b=(a-this.SM)/1E3,b="Over the past "+b.toFixed(1)+" seconds, sent "+(this.EB+" messages ("+Math.round(this.Nu/b)+" bytes/sec) and ")+("received "+this.DB+" messages ("+Math.round(this.Mu/b)+" ")+"bytes/sec).";this.bH(a);return b};var up=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},vp=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var wp=function(a,b,c,e,f){this.fh=new op(a,b,c,e,void 0===f?null:f);this.a=D("mr.mirror.cast.MediaStreamer");this.Kc=new So(1);this.Cv=this.Rb=this.Jb=this.rc=null};d=wp.prototype;d.start=function(a,b){var c=this;return this.Kc.Ef(1,function(e){c.rc=a;c.Jb=up(a);c.Jb&&"ended"==c.Jb.readyState&&(c.Jb=null);c.Rb=vp(a);c.Rb&&"ended"==c.Rb.readyState&&(c.Rb=null);if(!c.Jb&&!c.Rb)return e.complete(),Promise.reject(Error("No MediaStream tracks to stream."));c.Cv=b;return c.fh.start(c.Jb,c.Rb,b).then(function(){return e.complete(2)})})};
d.stop=function(){var a=this;return this.Kc.ay(function(b){return a.fh.stop().then(function(){a.Jb=null;a.Rb=null;a.rc=null;a.Cv=null;b.complete(1)})})};d.suspend=function(){var a=this;return this.Kc.Ef(2,function(b){a.a.info("Suspending media streaming...");return a.fh.stop().then(function(){a.a.info("Suspended media streaming.");b.complete(3)})})};
d.resume=function(){var a=this;return this.Kc.Ef(3,function(b){a.Jb&&"ended"==a.Jb.readyState&&(a.Jb=null);a.Rb&&"ended"==a.Rb.readyState&&(a.Rb=null);if(!a.Jb&&!a.Rb)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.a.info("Resuming media streaming...");return a.fh.start(a.Jb,a.Rb,a.Cv).then(function(){a.a.info("Resumed media streaming.");b.complete(2)})})};d.BG=function(){return this.fh.BG()};d.zj=function(a){return this.fh.zj(a)};d.getStats=function(a){return this.fh.getStats(a)};var xp=function(a,b,c){this.H=a;this.Li=b;this.Rd=c;this.a=D("mr.mirror.cast.WifiStatusMonitor");this.Gw=null;this.zo=[]};d=xp.prototype;d.Jj=function(){return null!=this.Gw};d.start=function(){var a=this;this.Jj()||(this.a.C("Starting Wifi Status Monitoring."),this.zo=[],this.Rd.subscribe("STATUS_RESPONSE",function(b){return a.Ica(b)}),this.Gw=setInterval(function(){return a.xV()},12E4),this.xV())};
d.stop=function(){this.Jj()&&(this.a.C("Stopping Wifi Status Monitoring."),clearInterval(this.Gw),this.Gw=null,this.Rd.unsubscribe("STATUS_RESPONSE"))};
d.Ica=function(a){if(this.Jj())if(a.status){var b={};null!=a.status.VI&&(b.wifiSnr=a.status.VI);null!=a.status.WI&&(b.wifiSpeed=a.status.WI[3]);0==Object.keys(b).length?this.a.u(function(){return"No status fields populated in response: "+JSON.stringify(a)}):(b.timestamp=Date.now(),30==this.zo.length&&this.zo.shift(),this.zo.push(b),this.a.info(function(){return"Current Wifi status: "+JSON.stringify(b)}))}else this.a.u(function(){return"Ignoring response without status: "+JSON.stringify(a)})};
d.xV=function(){this.Rd.sendMessage({type:"GET_STATUS",sessionId:this.H,seqNum:this.Li.Er(),get_status:["wifiSnr","wifiSpeed"]})};var yp=function(a,b,c){c=void 0===c?null:c;Ih.call(this,b);var e=b.lf;this.H=e.sessionId;this.jg=e.lI;this.Mb=a;this.Cz=c;this.a=D("mr.mirror.cast.Session");this.Kc=new So(1);this.Li=new oi("mirror.cast.SeqNumGenerator");this.Rd=new lp(b.id);this.Vl=new wp(e,this.Mb,this.Li,this.Rd,this.Cz);this.Ds=null;this.Xz=new xp(this.H,this.Li,this.Rd);this.CE=!1;this.fe=null};ja(yp,Ih);d=yp.prototype;
d.start=function(a){var b=this;return this.Kc.Ef(1,function(c){var e=new Yg("MediaRouter.CastStreaming.Session.Launch");return b.zaa().then(function(c){b.CE=c;return b.Vl.start(a,b.EF.bind(b))}).then(function(){b.Vl.BG()&&(b.Xz.start(),b.xaa());e.end();b.fe=new ch("MediaRouter.CastStreaming.Session.Length");c.complete(2);return b})})};
d.stop=function(){var a=this;return this.Kc.ay(function(b){a.fe&&(a.fe.end(),a.fe=null);a.Xz.stop();return a.Vl.stop().then(function(){return a.Ds?a.Ds.stop():Promise.resolve()}).then(function(){a.Ds=null;return a.CE?a.B3():Promise.resolve()}).then(function(){a.CE=!1;b.complete(4)})})};
d.rV=function(){var a={sessionId:this.H,seqNum:this.Li.Er(),type:"PRESENTATION",icons:[]};this.cy&&(a.title=this.cy);this.iconUrl&&!this.Jw&&a.icons.push({url:this.iconUrl});this.a.info("Sending session metadata update to receiver: "+this.H);this.Rd.sendMessage(a)};d.zj=function(){return this.Vl.zj(this.Xz.zo)};d.getStats=function(){return this.Vl.getStats(this.Xz.zo)};d.EF=function(a,b){this.a.error(a,b);this.stop()};
d.zaa=function(){var a=this;return this.Mb.useTdls?Ro(this.jg,!0).then(function(b){if("Connected"==b)return a.a.info("Successfully enabled TDLS."),!0;a.a.u("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.a.u("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)};d.B3=function(){var a=this;return Ro(this.jg,!1).catch(function(b){return a.a.error("Error while turning TDLS back off",b)})};
d.xaa=function(){var a=this;this.Jea().then(function(b){(b.IS||[]).includes("video")?a.Jla(b):a.a.u(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.a.u("None/Invalid capabilites response. Media Remoting disabled.",b)})};
d.Jea=function(){var a=this;return new Promise(function(b,c){var e={type:"GET_CAPABILITIES",sessionId:a.H,seqNum:a.Li.Er()};a.a.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(e)});a.Rd.SU(e,"CAPABILITIES_RESPONSE",3E4,function(f,h){if(null==f)return c(h),!0;if("ok"!=f.result||!f.capabilities)return c(Error("Bad response: "+JSON.stringify(f))),!0;if(f.nH!=e.seqNum)return a.a.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(f)}),
!1;a.a.C(function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(f)});b(f.capabilities);return!0})})};d.Jla=function(a){var b=this;this.Kc.Ef(2,function(c){b.Ds=new sp(b.Gb,a,b.Mb,b.Li,b.Rd,b.Cz);return b.Ds.start(b.ega.bind(b)).catch(function(a){b.a.error("Media Remoting start failed: "+a.message,a)}).then(function(){return c.complete()})})};
d.ega=function(){var a=this;return this.Kc.Ef(2,function(b){return new Promise(function(c,e){a.Vl.suspend().then(function(){b.complete(3);c(a.zga.bind(a))}).catch(function(b){a.EF("Failed to suspend MediaStreamer before starting remoting",b);e(b)})})})};d.zga=function(){var a=this;return this.Kc.Ef(3,function(b){return new Promise(function(c,e){a.Vl.resume().then(function(){b.complete(2);c()}).catch(function(b){a.EF("Failed resume MediaStreamer after ending remoting mode",b);e(b)})})})};var zp=function(){Gh.call(this,"cast_streaming");this.Cz=null};ja(zp,Gh);d=zp.prototype;d.getName=function(){return"cast_streaming"};d.gv=function(a,b){return new yp(a,b,this.Cz)};d.Yx=function(){Eo(0)};d.Ux=function(){Eo(1)};d.DG=function(){Eo(2)};d.Vx=function(){fh("MediaRouter.CastStreaming.Session.End")};d.Wx=function(a){gh("MediaRouter.CastStreaming.Start.Failure",a,ih)};d.Xx=function(){fh("MediaRouter.CastStreaming.Stream.End")};
d.RA=function(a){var b=this,c=a.zj().then(function(a){return a},function(a){b.A.u("Get cast streaming logs failed.",a)});a=a.getStats().then(function(a){return a},function(a){b.A.u("Get cast streaming stats failed.",a)});var e=new Promise(function(a){chrome.metricsPrivate.getIsCrashReportingEnabled(a)});return Promise.all([c,a,e]).then(function(a){var c=ia(a);a=c.next().value;var e=c.next().value,c=c.next().value;if(a){var f=new FileReader;f.onloadend=function(){ci("mr.temp.mirror.cast.Service.mirrorLogs",
f.result)};f.readAsBinaryString(a)}c&&(a&&Ko().tla()?Ho(a,void 0,b.xba.bind(b)):e&&Go("stats.json",new Blob([JSON.stringify(e)],{type:"application/json"}),void 0,void 0))})};d.xba=function(a){a&&Ko().jja(Date.now())};d.Ge=function(a){var b=this;this.A.info("Received message to upload logs for "+a);return this.Ma?this.Ma.zj().then(function(b){return Ho(b,a)},function(c){b.A.u("Get cast streaming logs failed.",c);return b.GS(a)}):Promise.resolve(this.GS(a))};
d.GS=function(a){var b=window.localStorage["mr.temp.mirror.cast.Service.mirrorLogs"];if(b){window.localStorage.removeItem("mr.temp.mirror.cast.Service.mirrorLogs");this.A.info("Uploading saved logs for feedback.");for(var c=new Uint8Array(b.length),e=0;e<c.length;e++)c[e]=b.charCodeAt(e);return Ho(new Blob([c],{type:"application/gzip"}),a)}};var Ap=new zp;Eh("mr.mirror.cast.Service",Ap);
